HealthCatalyst/Fabric.Cashmere

- .editorconfig
- package-lock.json
- package.json
- tsfmt.json
- tslint.json
This pull request is in response to issue #8.
I updated TSLint dependency because there was a bug with the version we have preventing me from validating that the es6 imports had a space. I've set the project to use spaces with an indentation of 2. I set that default because I like the smaller indentation, but we, as a team, should decide what indentation works best. 
I've also included typescript-formatter which is able to change the source code to match our code styling. The idea is that if you want to use the tool you could use a pre-commit hook
> Project Formatting

- .angular-cli.json
- package-lock.json
- src/styles.scss
the build is failing with `ERROR in ./node_modules/font-awesome/css/font-awesome.css Error: Cannot find module 'cuint' `
according to the docs we should be using font awesome differently. I know we want to get rid of it, but I am just trying to get the build working.
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-font-awesome.md
> fix build errors with font awesome

- LICENSE
- package.json
> License Cashmere as Apache 2.0

- src/app/app.module.ts
- src/app/demo/demo.module.ts
- src/app/integration-testing/select-integration-test.component.spec.ts
- src/app/integration-testing/select-integration-test.component.ts
- src/app/integration-testing/select-integration-test.module.ts
- src/app/lib/cashmere.ts
- src/app/lib/select/select-demo/select-demo.component.html
- src/app/lib/select/select.component.html
- src/app/lib/select/select.component.spec.ts
- src/app/lib/select/select.component.ts
- src/app/lib/select/select.module.ts
Implemented the `ControlValueAccessor` interface to ensure compatibility with angular forms. In order to properly test this, I created a test component that used the select component and used a reactive form. 
I did sneak in some exports to `cashmere.ts`
> Update SelectComponent to be compatible with Angular Forms

- src/app/demo/demo-routes.ts
- src/app/demo/demo.module.ts
- src/app/demo/side-nav/side-nav.component.html
- src/app/lib/cashmere.ts
- src/app/lib/drawer/drawer-container.component.html
- src/app/lib/drawer/drawer-container.component.scss
- src/app/lib/drawer/drawer-container.component.ts
- src/app/lib/drawer/drawer-demo/drawer-demo.component.html
- src/app/lib/drawer/drawer-demo/drawer-demo.component.ts
- src/app/lib/drawer/drawer.component.scss
- src/app/lib/drawer/drawer.component.ts
- src/app/lib/drawer/drawer.module.ts
- src/app/lib/drawer/index.ts
> Added drawer component

- src/app/lib/select/select.component.scss
> Hide default arrow in IE

- .travis.yml
- package.json
- scripts/travis-mode.sh
- scripts/travis-script.sh
- src/app/lib/cashmere.ts
- src/app/lib/drawer/drawer-container.component.ts
This is for issue #66 . @jtrujill for some reason barrels were causing rollup to fail when building the library. Also, I have no experience with travis and would love your expertise in looking over what I've done. I want to add as a check that the library is building when a pull request is submitted.
> Travis Package Library Check

- src/app/lib/button/anchor.component.ts
- src/app/lib/button/button-demo/button-demo.component.html
- src/app/lib/button/button.component.scss
- src/app/lib/button/button.component.spec.ts
- src/app/lib/button/button.component.ts
- src/app/lib/checkbox/checkbox.component.ts
- src/app/lib/drawer/drawer.component.ts
- src/app/lib/util.ts
- src/styles.scss
Added a util file, used hostbinding where possible, updated button class names and added a unit test for a missing case
> Button cleanup

- src/app/lib/app-switcher/app-switcher.component.html
- src/app/lib/app-switcher/app-switcher.component.scss
- src/app/lib/app-switcher/app-switcher.component.ts
- src/app/lib/navbar/navbar.component.scss
Minor adjustment to @benjanderson's amazing navBar.  Adds a hover state for the app switcher button to darken the background and keeps the dark background on until the popover is closed.  Thanks for your help with this one Ben!
> NavBar App Switcher Hover/On State

- package-lock.json
- src/app/demo/demo-routes.ts
- src/app/demo/demo.module.ts
- src/app/demo/side-nav/side-nav.component.html
- src/app/lib/cashmere.ts
- src/app/lib/icon/icon-demo/icon-demo.component.html
- src/app/lib/list/index.ts
- src/app/lib/list/list-demo/list-demo.component.html
- src/app/lib/list/list-demo/list-demo.component.scss
- src/app/lib/list/list-demo/list-demo.component.ts
- src/app/lib/list/list-item/directives/list-avatar.directive.ts
- src/app/lib/list/list-item/directives/list-icon.directive.ts
- src/app/lib/list/list-item/directives/list-line.directive.ts
- src/app/lib/list/list-item/index.ts
- src/app/lib/list/list-item/list-item.component.html
- src/app/lib/list/list-item/list-item.component.scss
- src/app/lib/list/list-item/list-item.component.ts
- src/app/lib/list/list.component.html
- src/app/lib/list/list.component.scss
- src/app/lib/list/list.component.spec.ts
- src/app/lib/list/list.component.ts
- src/app/lib/list/list.module.ts
> Added list component

- docs/app/demo/button/button-demo.component.html
- docs/app/demo/button/button-demo.component.scss
- lib/src/button/button.component.scss
- lib/src/button/button.component.spec.ts
- lib/src/button/button.component.ts
- lib/src/button/button.module.ts
- lib/src/button/index.ts
- lib/src/button/split-button/button-item.directive.ts
- lib/src/button/split-button/index.ts
- lib/src/button/split-button/split-button.component.html
- lib/src/button/split-button/split-button.component.spec.ts
- lib/src/button/split-button/split-button.component.ts
> Added split-button

- docs/app/demo/button/button-demo.component.html
- lib/src/button/button.component.scss
> Fixes Button Hover

- docs/styles.scss
- lib/src/tabs/tab-set.component.scss
> Fix vertical tab 100% height issue

- docs/app/components/components-routes.ts
- docs/app/components/components.module.ts
- docs/app/components/tabs/tab-demo.component.ts
- docs/app/components/tabs/tab1-demo.component.ts
- docs/app/components/tabs/tab2-demo.component.ts
- docs/app/components/tabs/tab3-demo.component.ts
- docs/app/components/tabs/tabs-demo.component.html
- docs/app/components/tabs/tabs-demo.component.ts
- lib/src/tabs/tab-set.component.ts
- lib/src/tabs/tab.component.ts
> Allow  routerlink as array or string; remove change after checked errors

- docs/app/components/components-routes.ts
- docs/app/components/components.component.html
- docs/app/components/components.module.ts
- docs/app/components/typeform-survey/typeform-survey-demo.component.html
- docs/app/components/typeform-survey/typeform-survey-demo.component.ts
- lib/package.json
- lib/public_api.ts
- lib/src/typeform-survey/index.ts
- lib/src/typeform-survey/typeform-survey.component.ts
- lib/src/typeform-survey/typeform-survey.module.ts
- package-lock.json
- package.json
> Create typeform survey component

- lib/src/checkbox/checkbox.component.html
- lib/src/checkbox/checkbox.component.scss
Super minor fine tuning of a couple things:
1. Vertical centering was off just a touch. Use flex-box to get this spot on. Should work even if font-size or size of the checkbox changes.
2. Hover effect was missing when you were hovering over the text label. Example, with current radio button for contrast:
> Fine tune the hover effects and positioning of the checkbox component.

- docs/app/components/pagination/pagination-demo.component.html
- lib/src/pagination/pagination.component.html
- lib/src/pagination/pagination.component.scss
@andrew-frueh sorry I didn't see your PR until after mine had landed.  I think it's great!
> Style tweaks to pagination as per Andrew Frueh

- docs/app/components/components.module.ts
- docs/app/components/select/select-demo.component.html
- docs/app/components/select/select-demo.component.ts
- lib/src/select/select.component.html
- lib/src/select/select.component.scss
- lib/src/select/select.component.ts
This has the same fix as PR #212 so if this gets accepted I'll close that
> Fixes #211 - select acts as a block element

- lib/src/sass/tables.scss
> remove position

- docs/app/app.component.html
> default guides to getting started to fix double click bug

- lib/src/input/input.component.scss
> Fix bug where inputs in IE are shorter than they ought to be.

- lib/package-lock.json
- lib/src/sass/_tabs.scss
- lib/src/tabs/tab-set.component.html
- lib/src/tabs/tab-set.component.ts
> Fix setting tab-set active tab when using dynamic content

- lib/src/pagination/pagination.component.html
- lib/src/pagination/pagination.component.scss
> Fix broken IE styles for pagination component

- guides/components/button.md
Fixes #227 
Eventually, jsdocs will cover us here. But until then...
> Add color options to button component docs

- angular.json
- package-lock.json
- projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
- projects/cashmere/src/lib/checkbox/checkbox-required.directive.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.html
- projects/cashmere/src/lib/checkbox/checkbox.component.scss
- projects/cashmere/src/lib/checkbox/checkbox.component.spec.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.ts
- projects/cashmere/src/lib/checkbox/checkbox.module.ts
- projects/cashmere/src/lib/checkbox/index.ts
- projects/cashmere/src/lib/navbar/navbar.component.scss
- projects/cashmere/src/lib/popover/popoverContent.component.scss
- projects/cashmere/src/lib/radio-button/radio-button.component.scss
- projects/cashmere/src/lib/sass/_reset.scss
- projects/cashmere/src/lib/sass/cashmere.scss
- src/app/components/chip/filter-button.component.scss
- src/app/components/picklist/picklist-demo.component.scss
- src/app/components/progress-indicator/progress-indicator-demo.component.scss
- src/app/components/subnav/subnav-demo.component.scss
- src/app/components/tabs/tabs-demo.component.scss
- src/app/home/home.component.scss
- src/app/styles/chart/barchart/barchart.component.scss
- src/app/styles/chart/chart-demo.component.scss
- src/app/styles/chart/linechart/linechart.component.scss
- src/app/styles/color/color-demo.component.scss
- src/app/styles/color/swatch-demo.component.scss
- src/styles.scss
* Added unit test for checkbox
* Added normalize.css to _reset.scss
> * Fixes several issues with checkbox

- README.md
- guides/contribution-guide.md
- guides/getting-started.md
- guides/packaging-library.md
> Updated guides and readme to reflect upgrade to angular-cli@6

- package-lock.json
- package.json
- projects/cashmere/src/lib/app-switcher/app-switcher-interfaces.ts
- projects/cashmere/src/lib/app-switcher/app-switcher.component.ts
- projects/cashmere/src/lib/app-switcher/app-switcher.service.ts
- projects/cashmere/src/lib/breadcrumbs/breadcrumbs.component.ts
- projects/cashmere/src/lib/modal/modal.ts
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.ts
- projects/cashmere/src/lib/picklist/pane/picklist-pane.component.ts
- projects/cashmere/src/lib/picklist/pane/picklist-pane.model.ts
- projects/cashmere/src/lib/picklist/picklist.model.ts
- projects/cashmere/src/lib/picklist/services/picklist-filter-remote.service.ts
- projects/cashmere/src/lib/picklist/services/picklist-filter.service.ts
- projects/cashmere/src/lib/picklist/services/work-tracker.service.ts
- src/app/components/picklist/picklist-demo-data.ts
- src/polyfills.ts
- tslint.json
> Added rxjs-lint, removed rxjs-appcompat

- .releaserc.json
- .travis.yml
- commitlint.config.js
- package-lock.json
- package.json
- projects/cashmere/package.json
- scripts/postbuild.js
- scripts/publish.sh
- scripts/replace-package-version.sh
- scripts/travis-script.sh
Added semantic-release to help with app versioning, release changes, git tagging and npm publishing.
Also added commit message linting and commitizen to help with writing commits
closes #83
> build: automate release

- .releaserc.json
- package-lock.json
- package.json
Added @semantic-release/git and @semantic-release/changelog to dev dependencies and removed
@semantic-release/git from publish step in .releaserc.json
> fix: fix semantic-release build

- .prettierignore
- .releaserc.json
- package-lock.json
- package.json
- projects/cashmere/package.json
- scripts/replace-package-version.sh
Fix semantic-release config so that it correctly adds a dist-tag to the published npm package. Fix
so it commits the updated package.json version
> fix: fix semantic-release dist-tag

- scripts/replace-package-version.sh
fix sed for linux by removing empty quotes(only needed for osx)
> fix: fix replace-package-version.sh

- guides/contribution-guide.md
included instructions for setting up the dev environment with commitizen
> docs(contribution-guide.md): update contribution guide

- package-lock.json
- scripts/replace-package-version.sh
replace-package-version.sh was using an incorrectly formatted sed script
> fix: fix incorrect package-lock version

- package-lock.json
- projects/cashmere/src/lib/progress-indicators/progress-dots.component.ts
- projects/cashmere/src/lib/progress-indicators/progress-spinner.component.html
- projects/cashmere/src/lib/progress-indicators/progress-spinner.component.spec.ts
- projects/cashmere/src/lib/progress-indicators/progress-spinner.component.ts
Added jsdoc comments for the public properties of the dot and spinner progress indicator components
re #307
> docs(progress indicators): add jsdoc comments

- tools/dgeni/common/decorators.ts
- tools/dgeni/common/dgeni-definitions.ts
- tools/dgeni/common/directive-metadata.ts
- tools/dgeni/common/normalize-method-parameters.ts
- tools/dgeni/common/property-bindings.ts
- tools/dgeni/common/sort-members.ts
- tools/dgeni/index.ts
- tools/dgeni/patch-log-service.ts
- tools/dgeni/processors/categorizer.ts
- tools/dgeni/processors/component-grouper.ts
- tools/dgeni/processors/docs-private-filter.ts
- tools/dgeni/processors/filter-duplicate-exports.ts
- tools/dgeni/processors/merge-inherited-properties.ts
- tools/dgeni/templates/class.template.html
- tools/dgeni/templates/common.template.html
- tools/dgeni/templates/componentGroup.template.html
- tools/dgeni/templates/interface.template.html
- tools/dgeni/templates/macros.html
- tools/dgeni/templates/method-list.template.html
- tools/dgeni/templates/method.template.html
- tools/dgeni/templates/property-list.template.html
- tools/dgeni/templates/property.template.html
fixes dgeni generated import statement for each component
> docs: fix docs import path

- projects/cashmere/src/lib/typeform-survey/typeform-survey.component.ts
> docs: add typeform-survey js docs

- projects/cashmere/src/lib/input/hc-error.component.ts
- projects/cashmere/src/lib/input/hc-form-field.component.ts
- projects/cashmere/src/lib/input/hc-label.component.ts
- projects/cashmere/src/lib/input/hc-prefix.directive.ts
- projects/cashmere/src/lib/input/hc-suffix.directive.ts
- projects/cashmere/src/lib/input/input.directive.ts
wrote descriptions for properties of components and gave descriptions for each directive/component
> docs(input component): improve dgeni docs

- projects/cashmere/src/lib/accordion/accordion-toolbar.component.ts
- projects/cashmere/src/lib/accordion/accordion.component.html
- projects/cashmere/src/lib/accordion/accordion.component.ts
documents accordion component's public api while hiding fields/methods that are private
close #293
> docs(accordion component): adds jsdoc comments to accordion component

- projects/cashmere/src/lib/drawer/drawer-container.component.ts
- projects/cashmere/src/lib/drawer/drawer.component.ts
documents drawer component's public api while hiding fields/methods that are private
close #298
> docs(drawer component): adds jsdoc comments to drawer component

- projects/cashmere/src/lib/button/anchor.component.ts
- projects/cashmere/src/lib/button/button.component.ts
- projects/cashmere/src/lib/button/split-button/button-item.directive.ts
- projects/cashmere/src/lib/button/split-button/split-button.component.html
- projects/cashmere/src/lib/button/split-button/split-button.component.ts
documents button component's public api while hiding fields/methods that are private
close #295
> docs(button component): adds jsdoc comments for button component

- projects/cashmere/README.md
- scripts/postbuild.js
adds readme for cashmere that's geared towards user's of the library
close #77
> docs: adds readme for cashmere lib

- projects/cashmere/src/lib/list/list-item/directives/list-avatar.directive.ts
- projects/cashmere/src/lib/list/list-item/directives/list-icon.directive.ts
- projects/cashmere/src/lib/list/list-item/directives/list-line.directive.ts
- projects/cashmere/src/lib/list/list-item/list-item.component.ts
- projects/cashmere/src/lib/list/list.component.ts
documents list component's public api while hiding fields/methods that are private
close #301
> docs(list component): adds jsdoc comments to list component

- projects/cashmere/src/lib/tabs/index.ts
- projects/cashmere/src/lib/tabs/tab-set.component.html
- projects/cashmere/src/lib/tabs/tab-set.component.ts
- projects/cashmere/src/lib/tabs/tab.component.ts
> docs: add tab js docs

- projects/cashmere/src/lib/modal/active-modal.ts
- projects/cashmere/src/lib/modal/modal-body.component.ts
- projects/cashmere/src/lib/modal/modal-footer.component.ts
- projects/cashmere/src/lib/modal/modal-header.component.ts
- projects/cashmere/src/lib/modal/modal-options.ts
- projects/cashmere/src/lib/modal/modal-overlay.component.ts
- projects/cashmere/src/lib/modal/modal-window.component.ts
- projects/cashmere/src/lib/modal/modal.component.ts
- projects/cashmere/src/lib/modal/modal.service.ts
- projects/cashmere/src/lib/modal/modal.spec.ts
- projects/cashmere/src/lib/modal/modal.ts
> docs: add modal documentation

- package-lock.json
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.html
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.spec.ts
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.ts
> fix: decouple mobile menu from IAppSwitcherService and document

- README.md
- package-lock.json
- projects/cashmere-examples/src/lib/picklist-simple/picklist-simple-example.html
- projects/cashmere-examples/src/lib/picklist-simple/picklist-simple-example.ts
- projects/cashmere-examples/src/lib/picklist-valueset/picklist-valueset-example.html
- projects/cashmere-examples/src/lib/picklist-valueset/picklist-valueset-example.ts
- projects/cashmere/src/lib/picklist/index.ts
- projects/cashmere/src/lib/picklist/pane/picklist-pane.component.scss
- projects/cashmere/src/lib/picklist/picklist.component.html
- projects/cashmere/src/lib/picklist/picklist.component.ts
- projects/cashmere/src/lib/picklist/picklist.model.ts
- projects/cashmere/src/lib/picklist/services/picklist-valueset-moving.service.ts
- projects/cashmere/src/lib/picklist/services/picklist.service.ts
- src/app/core/document-items.service.ts
> 305 picklist docs

- projects/cashmere/src/lib/radio-button/radio-button.component.html
- projects/cashmere/src/lib/radio-button/radio-button.component.ts
- projects/cashmere/src/lib/radio-button/radio-group.directive.ts
- src/app/components/component-viewer/component-api/document-viewer/document-viewer.component.scss
adds descriptions to radio button component; adds a few additional css classes to the dgeni styling to improve the readability of the "methods" section.
@nickrflynn and @ckeates - hoping you can both give this a look over because you've worked on it and know this component better than me.  I took at stab at the documentation descriptions, but please let me know if there's anything you would change.
closes #308
> docs: add jsdocs to radio button

- projects/cashmere/src/lib/checkbox/checkbox-required.directive.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.html
- projects/cashmere/src/lib/checkbox/checkbox.component.spec.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.ts
documents checkbox component's public api while hiding fields/methods that are private
close #296
> docs(checkbox): adds jsdoc comments to checkbox component

- README.md
added link to the changelog found on the master branch to the readme
close #376
> docs(readme.md): added changelog to readme

- projects/cashmere/src/lib/pagination/pagination.component.html
- projects/cashmere/src/lib/pagination/pagination.component.spec.ts
- projects/cashmere/src/lib/pagination/pagination.component.ts
- projects/cashmere/src/lib/pagination/pagination.md
- src/app/core/document-items.service.ts
documents pagination component's public api while hiding fields/methods that are private
close #304
> docs(pagination): update documentation for Pagination control

- projects/cashmere/src/lib/navbar/navbar-icon/navbar-icon.component.ts
- projects/cashmere/src/lib/navbar/navbar-link/navbar-link.component.html
- projects/cashmere/src/lib/navbar/navbar-link/navbar-link.component.ts
- projects/cashmere/src/lib/navbar/navbar.component.html
- projects/cashmere/src/lib/navbar/navbar.component.ts
> docs(navbar): add missing documentation

- projects/cashmere/src/lib/sass/tables.scss
> fix(table styles): minor table style fixes

- projects/cashmere/src/lib/sass/tables.scss
Totally didn't think about how I need the Travis CI to be in charge of creating the release so I merged Cory's stuff so that I could trigger this thing
> merged dev into master

- projects/cashmere/src/lib/accordion/accordion.component.scss
sets accordion background color to inherit from parent
fix #399
> fix(accordion.component.scss): fixes accordion background color

- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example-dialog.html
- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.html
- src/app/styles/chart/chart-demo.component.html
updates components that used the button tertiary color to the new buttonStyle link
fix #420
> fix: fix invalid button color usage

- guides/getting-started.md
> docs(getting-started.md): adds @angular/cdk dep to getting-started

- projects/cashmere/src/lib/popover/popover.directive.ts
> fix(popover): click away to close by default

- projects/cashmere-examples/src/lib/select-disabled/select-disabled-example.css
- projects/cashmere-examples/src/lib/select-standard/select-standard-example.css
- projects/cashmere-examples/src/lib/select-validation/select-validation-example.css
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.html
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.spec.ts
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.ts
- projects/cashmere/src/lib/navbar/navbar.component.ts
- projects/cashmere/src/lib/sass/_subnav.scss
- projects/cashmere/src/lib/select/select.component.scss
- src/app/app.component.html
- src/app/components/components.component.html
- src/app/components/components.component.ts
- src/app/guides/guides.component.ts
- src/app/styles/styles.component.ts
- src/styles.scss
fixes responsive behavior on the docs site that had broken over time previous updates
@benjanderson and I noticed that the app switcher functionality is broken on the navbar mobile menu.  So that has been commented out until Ben has a chance to take a look at it.  I'll reopen the issue where we thought we fixed. 
closes #267
> fix(responsive): docs site

- projects/cashmere/src/lib/input/hc-form-field.component.scss
adjusts input's infix padding to match select components height
closes #335
> fix(input): infix padding

- projects/cashmere-examples/src/lib/accordion-overview/accordion-overview-example.html
- projects/cashmere-examples/src/lib/accordion-overview/accordion-overview-example.ts
- projects/cashmere/src/lib/accordion/accordion.component.html
- projects/cashmere/src/lib/accordion/accordion.component.scss
- projects/cashmere/src/lib/accordion/accordion.component.ts
adds ability to specify if entire toolbar is clickable or just the arrow; also updates the example to demo the capability
closes #422
> feat(accordion): toolbar trigger

- projects/cashmere-examples/src/lib/button-icon/button-icon-example.css
- projects/cashmere-examples/src/lib/button-icon/button-icon-example.html
- projects/cashmere-examples/src/lib/button-icon/button-icon-example.ts
- projects/cashmere/src/lib/button/button.component.scss
- projects/cashmere/src/lib/button/button.component.ts
> feat(button): adds icon button

- projects/cashmere/src/lib/app-switcher/app-switcher.component.html
- projects/cashmere/src/lib/app-switcher/app-switcher.component.ts
Remove the hardcoded brand icon and allow user to configure this icon
Fixes #439
> Allow user defined brand icon in AppSwitcher

- projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.css
- projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.html
- projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.ts
- projects/cashmere/src/lib/drawer/drawer-container.component.html
- projects/cashmere/src/lib/drawer/drawer-container.component.ts
- projects/cashmere/src/lib/drawer/drawer.component.scss
- projects/cashmere/src/lib/drawer/drawer.component.ts
- projects/cashmere/src/lib/drawer/drawer.module.ts
- projects/cashmere/src/lib/drawer/index.ts
- projects/cashmere/src/lib/drawer/menu-drawer/drawer-header.directive.ts
- projects/cashmere/src/lib/drawer/menu-drawer/drawer-item.component.ts
- projects/cashmere/src/lib/drawer/menu-drawer/menu-drawer.component.html
- projects/cashmere/src/lib/drawer/menu-drawer/menu-drawer.component.scss
- projects/cashmere/src/lib/drawer/menu-drawer/menu-drawer.component.ts
- src/app/core/document-items.service.ts
- tslint.json
> feat(drawer): adds a dark themed drawer menu

- projects/cashmere/src/lib/app-switcher/app-switcher.component.html
- projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
- projects/cashmere/src/lib/navbar/navbar.component.scss
Remove erroneous greater than sign that snuck in. Remove dark blue background on hover and focus.
> fix(app-switcher): remove erroneous greater than sign

- projects/cashmere-examples/src/lib/select-forms/select-forms-example.css
- projects/cashmere-examples/src/lib/select-forms/select-forms-example.html
- projects/cashmere-examples/src/lib/select-forms/select-forms-example.ts
- projects/cashmere/src/lib/breadcrumbs/breadcrumbs.component.spec.ts
- projects/cashmere/src/lib/chip/chip.component.spec.ts
- projects/cashmere/src/lib/label/label.component.spec.ts
- projects/cashmere/src/lib/select/select.component.html
- projects/cashmere/src/lib/select/select.component.ts
- projects/cashmere/src/lib/subnav/subnav.component.spec.ts
- projects/cashmere/src/lib/tabs/tab-set.component.spec.ts
- src/app/core/document-items.service.ts
> fix(select): fixes forms issue with select component

- projects/cashmere/src/lib/sass/_variables.scss
> fix(variables.scss): changes zindex of popover to be less than modal

- guides/styles/about-modal.md
- projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.html
- projects/cashmere/src/lib/navbar/navbar.md
- src/app/core/document-items.service.ts
- src/app/guides/guides.service.ts
moves the help menu guide to navbar component usage doc
closes #473
> docs(help menu): help menu guide

- package-lock.json
- projects/cashmere-examples/src/lib/pagination-overview/pagination-overview-example.html
- projects/cashmere-examples/src/lib/pagination-overview/pagination-overview-example.ts
- projects/cashmere/src/lib/button/button.component.scss
- projects/cashmere/src/lib/pagination/pagination.component.html
- projects/cashmere/src/lib/pagination/pagination.component.scss
- projects/cashmere/src/lib/pagination/pagination.component.spec.ts
- projects/cashmere/src/lib/pagination/pagination.component.ts
- projects/cashmere/src/lib/pagination/pagination.module.ts
- projects/cashmere/src/lib/select/select.component.scss
BREAKING CHANGE: replaced totalPages input with length input
closes #451, fixes #445, fixes #316, fixes #478
> feat(pagination): add page size

- projects/cashmere/src/lib/modal/modal.ts
> fix(modal): fixes modal result so it doesn't expose the Subject

- package-lock.json
- package.json
- projects/cashmere-examples/src/lib/table-overview/table-overview-example.html
- projects/cashmere-examples/src/lib/table-overview/table-overview-example.ts
- projects/cashmere/src/lib/sass/tables.scss
- projects/cashmere/src/lib/table/table.component.scss
This PR proposes changes to the hc-table to bring it into alignment with @andrew-frueh's designs (https://xd.adobe.com/view/55c8964a-fe2f-41c3-4ede-3d1bbd4d5b71-23f9/screen/ea040736-2e21-46f1-a57e-20275e50b077/Expense-Region/). It also adds a footer row to the Example Overview Table in the documentation to better demonstrate the functionality and style of footer rows.
> refactor(hc-table): update hc-table styles to match official designs

- projects/cashmere/src/lib/accordion/accordion.component.ts
- projects/cashmere/src/lib/chip/chip.component.ts
- projects/cashmere/src/lib/drawer/drawer.component.ts
- projects/cashmere/src/lib/progress-indicators/progress-dots.component.ts
- projects/cashmere/src/lib/progress-indicators/progress-spinner.component.ts
- projects/cashmere/src/lib/tabs/tab-set.component.ts
I was looking for a quick issue to pick off this afternoon, so I grabbed this one.  Adds a validation check to string inputs on several components.  Throws a formatted error if the string is invalid to help out the developer.  Follows the pattern established in the button component.
closes #407
> test(multiple): string input validation

- guides/using-and-customizing-components.md
- projects/cashmere/src/lib/button/button.component.scss
- projects/cashmere/src/lib/sass/button.scss
Is there a way to test this as if it were a published NPM package so I can document the process of using Cashmere via mixins?
Fixes #511
> refactor(button): convert button to mixins

- projects/cashmere-examples/src/lib/table-sort/table-sort-example.html
- projects/cashmere/src/lib/sort/sort-header.html
- projects/cashmere/src/lib/sort/sort-header.scss
- projects/cashmere/src/lib/sort/sort-header.ts
Updates the table component sort headers to match our [Health Catalyst style](https://cashmere.healthcatalyst.net/styles/table).  Uses encoded svgs for the icons, so no dependency on FontAwesome.
closes #412
> style(table): updated sorting indicators

- projects/cashmere/src/lib/checkbox/checkbox.component.scss
- projects/cashmere/src/lib/sass/checkbox.scss
> refactor(checkbox): convert checkbox to use mixins

- projects/cashmere/src/lib/input/hc-form-field.component.scss
- projects/cashmere/src/lib/input/input.scss
- projects/cashmere/src/lib/sass/form-field.scss
- projects/cashmere/src/lib/sass/input.scss
> 516 convert input

- projects/cashmere/src/lib/button/split-button/split-button.component.scss
- projects/cashmere/src/lib/sass/button.scss
- projects/cashmere/src/lib/sass/cashmere.scss
- projects/cashmere/src/lib/sass/popover.scss
and move general popover styles to popover.scss
fix #545
> refactor(split-button): convert split-button to mixins

- projects/cashmere-examples/src/lib/table-filter/table-filter-example.html
- projects/cashmere-examples/src/lib/table-filter/table-filter-example.ts
- projects/cashmere/src/lib/sass/tables.scss
- projects/cashmere/src/lib/sort/sort-header.scss
- projects/cashmere/src/lib/table/table.component.ts
- src/app/styles/table/table-demo.component.html
As per the conversation on Slack today, adds a parameter to set whether the table component has solid borders or not.
closes #558
> style(table): optional borders

- projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.css
- projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.html
- projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.scss
- projects/cashmere/src/lib/checkbox/checkbox.component.ts
- projects/cashmere/src/lib/form-field/hc-form-control.component.ts
- projects/cashmere/src/lib/form-field/hc-form-field.component.html
- projects/cashmere/src/lib/form-field/hc-form-field.component.ts
- projects/cashmere/src/lib/input/input.directive.ts
- projects/cashmere/src/lib/sass/checkbox.scss
- projects/cashmere/src/lib/sass/form-field.scss
- projects/cashmere/src/lib/select/select.component.ts
adds form-field support for checkbox and updates example
closes #565, closes #582
> feat(checkbox): form-field support

- guides/contribution-guide.md
- package.json
add instructions on which commands to run while developing, and some helpful tips for windows users
> docs(contribution guide): tweak contribution guide

- projects/cashmere/src/lib/table/table-data-source.spec.ts
- projects/cashmere/src/lib/table/table-data-source.ts
incorrect page was sometimes being set when data was added after data source creation
fix #602
> fix(table data source): fix paging issue

- projects/cashmere-examples/src/lib/pagination-simple/pagination-simple-example.html
- projects/cashmere-examples/src/lib/pagination-simple/pagination-simple-example.ts
- projects/cashmere/src/lib/pagination/base-pagination.ts
- projects/cashmere/src/lib/pagination/pagination.component.spec.ts
- src/app/core/document-items.service.ts
provide output properties to bind to both pageNumberChange and pageSizeChange in addition to the
page event; schedule a macrotask for correcting bad input for pageNumber of the pagination component
fix #630
> fix(pagination): fix pagination event for invalid input

- projects/cashmere/src/lib/modal/modal.ts
> Skip null results when clicking off modal to dismiss

- projects/cashmere-examples/src/lib/table-sort/table-sort-example.ts
- projects/cashmere/src/lib/sass/_variables.scss
- projects/cashmere/src/lib/table/table-data-source.ts
- projects/cashmere/src/lib/table/table.md
Sort like this 'AaBbCc' instead of this 'ABCabc'
re #661
> fix(table data source): change default sort

- projects/cashmere/src/lib/toaster/hc-toaster.service.ts
fixes error thrown when toast is closed before timeout
> fix(toasts): toast timeout

- projects/cashmere/src/lib/sass/navbar.scss
prevent navbar-brand from shrinking below 55px width
closes #678
> fix(navbar): navbar-brand min-width

- src/app/home/home.component.scss
Corrections to the demo site home page for IE11
closes #697
> fix(home): IE11 css fixes

- projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
corrects app switcher thumbnail spacing on IE11
closes #693
> fix(app-switcher): IE11 thumbnail spacing

- projects/cashmere-examples/src/lib/progress-dots/progress-dots-example.component.scss
corrects progress indicator examples from being squished on load
closes #695
> fix(progress-indicators): example height fix

- projects/cashmere/src/lib/datepicker/calendar/calendar-header.html
https://material.angular.io/cdk/a11y/api#CdkAriaLive fixes issue where angular cdk would announce the button content to screen reader. It would be great to put accessibility into the library, but that is a whole different issue to tackle and I think it would be better to plan it out than to implement it without a goal or direction
Fixes #706
> fix(datepicker): fixed date showing at bottom #706

- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
> fix(date-range): min and max dates not working

- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
> fix(date-range): presets cant be selected twice

- projects/cashmere/src/lib/breadcrumbs/breadcrumbs.component.html
- projects/cashmere/src/lib/breadcrumbs/breadcrumbs.component.ts
Propogate the query parameters when using the breadcrumb component
fix #740
> Breadcrumb query parameters

- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.html
- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
- projects/cashmere/src/lib/datepicker/calendar-body/calendar-body.component.scss
- projects/cashmere/src/lib/datepicker/calendar/calendar-header.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
fix various issues found in date picker and date range.
> Date picker range bugs

- README.md
- guides/contribution-guide.md
These changes take into account that not all users or contributors have globally installed npm
packages. This also helps negate differences between versions of globally and project specific
packages.
> docs(guide): update guide docs to use Cashmere packages

- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.scss
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.scss
> fix(date-range): fixed long error message on invalid date layout issues

- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
this is embarrassing, I will wait for a review this time 😢
> fix(date-range): fix dumb missing css class

- projects/cashmere/src/lib/subnav/subnav.component.spec.ts
Adds unit test for the subnav component.  Not a whole lot to test in this one, so it's pretty simple.
closes #625
> test(subnav): add unit tests

- projects/cashmere/src/lib/icon/icon.component.spec.ts
adds unit tests for the Icon component
closes #573
> test(icon): add unit tests

- projects/cashmere/src/lib/chip/chip.component.spec.ts
adds unit test for the chip and chip row components
closes #571
> test(chips): adds unit tests

- projects/cashmere/src/lib/accordion/accordion.component.spec.ts
- projects/cashmere/src/lib/accordion/accordion.component.ts
adds unit tests for component and adds two-way binding to open property
closes #568
> test(accordion): adds unit tests

- src/app/styles/icons/icon-guide.component.html
corrects link to icon zip
closes #834
> fix(icons): link fix

- projects/cashmere/src/lib/toaster/hc-toast-ref.ts
stops toast reference from allowing multiple close calls
closes #849
> fix(toasts): ignore multiple close calls

- projects/cashmere-examples/src/project-template/src/app/app.component.ts
> docs(stackblitz app.component): import styles

- projects/cashmere/src/lib/modal/modal.ts
> fix: removed filtering null results out of modal

- projects/cashmere/src/lib/pop/popover.component.scss
- projects/cashmere/src/lib/sass/_cdk-overlay.scss
- projects/cashmere/src/lib/sass/_menu.scss
- projects/cashmere/src/lib/sass/_variables.scss
- projects/cashmere/src/lib/sass/cashmere.scss
fix datepicker appearing underneath a modal instead of above it
fix #867
> fix(datepicker): fix implementation of datepicker inside a modal

- projects/cashmere/package.json
- projects/cashmere/src/lib/scroll-nav/content/scroll-nav-content.component.ts
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav-link.directive.ts
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.scss
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.ts
> 877 scroll nav updates

- projects/cashmere-examples/src/lib/scroll-nav/scroll-nav-example.component.html
- projects/cashmere/src/lib/scroll-nav/content/scroll-nav-content.component.html
- projects/cashmere/src/lib/scroll-nav/content/scroll-nav-content.component.scss
- projects/cashmere/src/lib/scroll-nav/content/scroll-nav-content.component.ts
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav-link.directive.ts
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.ts
- projects/cashmere/src/lib/scroll-nav/scroll-nav.module.ts
re #885
- makes scroll behavior configurable
- tightens up docs
Minor stuff, just saw the need and wanted to get this in.
> fix(scroll-nav): tighten docs and add needed configuration propery

- .travis.yml
- scripts/publish-next.sh
Okay, I think this will fix the builds from PRs. Will wait to request review until it passes.
> Fix travis pr build maybe

- projects/cashmere-examples/src/lib/button-size/button-size-example.component.html
- projects/cashmere-examples/src/lib/button-split/button-split-example.component.html
- projects/cashmere/src/lib/button/split-button/split-button.component.html
anchor the dropdown to the entire split button, not just arrow btn trigger portion
re #914
> fix(split-button): change dropdown anchoring

- projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.scss
- projects/cashmere-examples/src/lib/drawer-overlay/drawer-overlay-example.component.scss
- projects/cashmere-examples/src/lib/drawer-side/drawer-side-example.component.scss
- projects/cashmere/src/lib/sass/menu-drawer.scss
adjusts the suggested filter drawer colors to be ADA compliant
closes #913
> style(drawer): ADA color contrast

- projects/cashmere/src/lib/datepicker/datepicker.component.ts
see the issue for details
fixes #925
> fix(datepicker): use correct import for DOCUMENT

- projects/cashmere/src/lib/form-field/hc-form-control.component.ts
- projects/cashmere/src/lib/form-field/hc-form-field.module.ts
also make it an abstract class
Closes #927
> fix(form-control): remove component decorator

- guides/styles/trademarks.md
- src/app/styles/styles-routes.module.ts
- src/app/styles/styles.component.html
- src/app/styles/styles.module.ts
- src/app/styles/trademarks/trademarks-demo.component.ts
One additional section from marketing styles and small reorganization of style sections as per Marketing's feedback.
Quick review would be appreciated on this out and marketing can pull their old site down.  Thanks!
closes #906
> docs(trademarks): adds trademarks section

- projects/cashmere/src/lib/pagination/load-more-pagination.component.html
- projects/cashmere/src/lib/pagination/load-more-pagination.component.scss
- projects/cashmere/src/lib/pagination/pagination.component.html
- projects/cashmere/src/lib/pagination/pagination.component.scss
- projects/cashmere/src/lib/sass/pagination.scss
> refactor(pagination): convert to mixins

- projects/cashmere/src/lib/modal/modal-window.component.scss
- projects/cashmere/src/lib/sass/button.scss
- projects/cashmere/src/lib/sass/checkbox.scss
- projects/cashmere/src/lib/sass/chip.scss
- projects/cashmere/src/lib/sass/form-field.scss
- projects/cashmere/src/lib/sass/modal.scss
- projects/cashmere/src/lib/sass/picklist-pane.scss
- projects/cashmere/src/lib/sass/picklist.scss
fixes #518.
Also fixes #935. Just needed to shorten some paths.
> refactor(modal): convert modal to mixins

- projects/cashmere/src/lib/toaster/hc-toaster.service.ts
Prevent error due to improper unsubscription. Instead of manually unsubscribing in hc-toaster.service, use the takeUntil() syntax. I believe this helps avoid prematurely unsubscribing, which for some reason only IE and Edge do not like.
fix #957
> fix(hc-toast): fix IE & Edge bug

- projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.html
- projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.scss
- projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.ts
- projects/cashmere/src/lib/toaster/hc-toast-options.ts
- projects/cashmere/src/lib/toaster/hc-toast-ref.ts
- projects/cashmere/src/lib/toaster/hc-toast.component.html
- projects/cashmere/src/lib/toaster/hc-toast.component.scss
- projects/cashmere/src/lib/toaster/hc-toast.component.ts
- projects/cashmere/src/lib/toaster/hc-toaster.service.ts
Added the option to include a progress bar. 
Added a width configuration and set the default toast width to 300px.
Increased toast body font size.
closes #943
> 943 toast items

- projects/cashmere/src/lib/datepicker/datepicker.md
- scripts/generate-usage-docs.js
allow html tags in usage markdown & update anchor links for datepicker
closes #883
> docs(usage): allow html in usage markdown

- guides/contribution-guide.md
- guides/getting-started.md
- guides/using-and-customizing-components.md
- guides/working-with-examples.md
- src/styles.scss
Corrects ordered list margin and several header and tile inconsistencies.  @isaaclyman - technical writing is definitely your domain, so if there are any other inconsistencies you see in our contribution guides, feel free to push to this PR.
closes #962
closes #931
> docs(guides): styles & formatting cleanup

- projects/cashmere-examples/src/lib/button-split/button-split-example.component.html
- projects/cashmere/src/lib/button/button.component.scss
- projects/cashmere/src/lib/sass/button.scss
adds split-button support for the minimal button style
@corykon - what do you think about this styling for a minimal split button?
closes #890
> fix(split-button): minimal split buttons

- projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts
- projects/cashmere/src/lib/datepicker/calendar/calendar-header.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.scss
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
- projects/cashmere/src/lib/datepicker/datepicker-intl.ts
- projects/cashmere/src/lib/datepicker/datepicker.component.scss
Adjusted header elements to address UX concerns that Alejo uncovered in his usability testing.
Closes #985 
Closes #703
> fix(datepicker): improved header labeling

- projects/cashmere/src/lib/form-field/hc-form-field.component.html
- projects/cashmere/src/lib/form-field/hc-form-field.component.scss
- projects/cashmere/src/lib/form-field/hc-form-field.component.spec.ts
- projects/cashmere/src/lib/form-field/hc-form-field.component.ts
- projects/cashmere/src/lib/sass/form-field.scss
Removes label wrappers if no labels are present.
closes #986
> fix(form-field): support for no labels

- projects/cashmere/src/lib/modal/modal.service.ts
- projects/cashmere/src/lib/modal/modal.ts
Adds a flag to ModalService to restrict multiple modals being opened.
closes #959
> fix(modal): restrict multiple modals

- projects/cashmere/src/lib/datepicker/datepicker-toggle/datepicker-toggle.component.html
- projects/cashmere/src/lib/datepicker/datepicker-toggle/datepicker-toggle.component.scss
correct sets focus on toggle button when selected
closes #1025
> fix(datepicker): toggle button focus

- projects/cashmere/src/lib/typeform-survey/typeform-survey.component.ts
allow updates to appVersion and surveyUri after the component is initialized
fix #984
> fix(typeform survey): allow updates after initialization

- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.spec.ts
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
check an approproate preset if the currently selected range matches it
closes #939
> fix(daterange): highlight preset on date change

- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
allow the defaultTab parameter to accept either a string or a number
closes #1021
> fix(tabs): defaultTab accepts number

- projects/cashmere-examples/src/lib/chip-action/chip-action-example.component.html
- projects/cashmere-examples/src/lib/chip-action/chip-action-example.component.scss
- projects/cashmere-examples/src/lib/chip-action/chip-action-example.component.ts
- projects/cashmere-examples/src/lib/chip-row/chip-row-example.component.html
- projects/cashmere-examples/src/lib/chip-row/chip-row-example.component.ts
- projects/cashmere-examples/src/lib/chip-singlerow/chip-singlerow-example.component.html
- projects/cashmere-examples/src/lib/chip-singlerow/chip-singlerow-example.component.ts
- projects/cashmere/src/lib/chip/chip.component.html
- projects/cashmere/src/lib/chip/chip.component.spec.ts
- projects/cashmere/src/lib/chip/chip.component.ts
- projects/cashmere/src/lib/sass/chip.scss
When I looked into #1040, I realized our chip examples were pretty hard-coded.  Seemed like there was a better way to do those.  This PR is my attempt to improve them - but I suspect you all might have ideas to improve what I have here.  All suggestions welcome. 
closes #1040
> fix(chips): improved examples

- guides/styles/trademarks.md
> docs(trademarks): update trademarks section

- package-lock.json
- package.json
- src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.html
- src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.ts
- src/app/components/components.component.ts
- src/app/components/components.module.ts
- src/app/guides/guides.component.ts
- src/app/guides/guides.module.ts
- src/app/shared/application-insights/application-insights.service.spec.ts
- src/app/shared/application-insights/application-insights.service.ts
- src/app/styles/styles.component.ts
- src/app/styles/styles.module.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
adds Azure Application Insights page view tracking
> docs(app): applications insights

- guides/styles/trademarks.md
Requested changes to usage guidelines section
closes #1050
> docs(trademarks): updated usage guidelines

- projects/cashmere-examples/src/lib/date-range-time/date-range-time-example.component.html
- projects/cashmere-examples/src/lib/date-range-time/date-range-time-example.component.ts
- projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
- projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.scss
- projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts
- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.html
- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
- projects/cashmere/src/lib/date-range/model/model.ts
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
- projects/cashmere/src/lib/date-range/services/config-store.service.ts
- projects/cashmere/src/lib/datepicker/calendar/calendar-header.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.scss
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
- projects/cashmere/src/lib/datepicker/datepicker-content/datepicker-content.component.html
- projects/cashmere/src/lib/datepicker/datepicker-content/datepicker-content.component.ts
- projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts
- projects/cashmere/src/lib/datepicker/datepicker-toggle/datepicker-toggle.component.html
- projects/cashmere/src/lib/datepicker/datepicker.component.scss
- projects/cashmere/src/lib/datepicker/datepicker.component.spec.ts
- projects/cashmere/src/lib/datepicker/datepicker.component.ts
- projects/cashmere/src/lib/datepicker/datepicker.module.ts
- projects/cashmere/src/lib/datepicker/datetime/date-adapter.ts
- projects/cashmere/src/lib/datepicker/datetime/date-formats.ts
- projects/cashmere/src/lib/datepicker/datetime/native-date-adapter.ts
- projects/cashmere/src/lib/datepicker/datetime/native-date-formats.ts
- projects/cashmere/src/lib/datepicker/month-view/month-view.component.ts
- projects/cashmere/src/lib/sass/form-field.scss
- src/app/core/document-items.service.ts
Adds time and date-time options to datepicker and daterange (see screenshots below).  I'll schedule a time for us all to review this big PR.
closes #946
**Time Picker**
**Time Range**
> feat(datepicker): time picker

- projects/cashmere/src/lib/app-switcher/app-switcher.component.html
- projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
- projects/cashmere/src/lib/app-switcher/app-switcher.component.spec.ts
Adjustments to the css naming on the app switcher to match our current conventions.
> style(app-switcher): css renaming

- package.json
Working with Joe and Andrew to update dependencies on the doc project.
> refactor(package): update package versions

- projects/cashmere/src/lib/sass/sort.scss
- projects/cashmere/src/lib/sort/sort-header.html
- projects/cashmere/src/lib/sort/sort-header.scss
> refactor(sort): convert to mixins

- projects/cashmere/src/lib/sass/select.scss
- projects/cashmere/src/lib/select/select.component.scss
> refactor(select): convert to mixins

- projects/cashmere/src/lib/form-field/hc-form-control.component.ts
- projects/cashmere/src/lib/form-field/hc-form-field.component.html
- projects/cashmere/src/lib/form-field/hc-form-field.component.ts
- projects/cashmere/src/lib/select/index.ts
- projects/cashmere/src/lib/select/select.component.html
- projects/cashmere/src/lib/select/select.component.ts
support better error messages with a rich error object for hcFormControlComponent and better change
event support for select component
> feat(dynamic input support): richer errors & better select change event

- projects/cashmere/src/lib/datepicker/calendar/calendar-header.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.html
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.scss
- projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
moved the jump to today button to header
re #946
> refactor(datepicker): refresh styles

- projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
- projects/cashmere-examples/src/lib/date-range/date-range-example.component.scss
- projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts
- projects/cashmere/src/lib/date-range/date-range/date-range.directive.spec.ts
- projects/cashmere/src/lib/date-range/date-range/date-range.directive.ts
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
- projects/cashmere/src/lib/date-range/services/config-store.service.ts
adds alternate emitter of preset index or daterange (if no preset)
closes #1095
> feat(daterange): selected preset emitter

- projects/cashmere-examples/src/lib/picklist-simple/picklist-simple-example.component.html
- projects/cashmere/src/lib/picklist/pane/picklist-pane.model.ts
- projects/cashmere/src/lib/picklist/picklist.component.ts
- projects/cashmere/src/lib/picklist/picklist.model.ts
- projects/cashmere/src/lib/picklist/services/picklist-filter-local.service.ts
- projects/cashmere/src/lib/picklist/services/picklist-state.service.ts
> fix(picklist): introduce config for sorting

- projects/cashmere-examples/src/lib/checkbox-standard/checkbox-standard-example.component.html
- projects/cashmere/src/lib/checkbox/checkbox.component.scss
- projects/cashmere/src/lib/sass/checkbox.scss
> fix(checkbox): fix disabled styling

- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.ts
- projects/cashmere/src/lib/icon/icon.component.ts
- projects/cashmere/src/lib/icon/index.ts
- projects/cashmere/src/lib/navbar/navbar.component.html
- projects/cashmere/src/lib/navbar/navbar.component.ts
- projects/cashmere/src/lib/sass/navbar.scss
adds support for using font icons in brand as well as images
closes #873
> feat(navbar): icons in brand

- projects/cashmere-examples/src/lib/pagination-load-more/pagination-load-more-example.component.ts
- projects/cashmere-examples/src/lib/pagination-standard/pagination-standard-example.component.ts
Switches example from OnInit to AfterViewInit. Great catch on this one @waldnercharles!
closes #1038
> docs(pagination): change to AfterViewInit

- projects/cashmere/src/lib/modal/active-modal.ts
make the ActiveModal class generic so data can be strongly typed
closes #1033
> refactor(activemodal): make class generic

- src/app/styles/typography/typography-demo.component.html
Adds links to download our two icon fonts.
closes #1090
> docs(typography): icon font links

- projects/cashmere/src/lib/sass/checkbox.scss
convert checkmark to base64 image rather than css transform
any concerns with this change @corykon?
closes #1053
> refactor(checkbox): base64 checkmark

- projects/cashmere-examples/src/lib/popover-menu/popover-menu-example.component.html
- projects/cashmere-examples/src/lib/popover-menu/popover-menu-example.component.ts
- projects/cashmere/src/lib/pop/directives/menu.directive.ts
- projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
- projects/cashmere/src/lib/pop/popover-anchoring.service.ts
- projects/cashmere/src/lib/pop/popover.component.ts
- projects/cashmere/src/lib/sass/_menu.scss
allows hcMenus in hcPop to support submenus
closes #1089
> feat(pop): submenus

- projects/cashmere/src/lib/form-field/hc-form-field.component.scss
- projects/cashmere/src/lib/sass/form-field.scss
- projects/cashmere/src/lib/sass/select.scss
- projects/cashmere/src/lib/select/select.component.scss
adjusts border width to 1.5px on all modern browsers
closes #643
> style(input): thinner borders

- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.html
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
allows the app to set if the tab-set will create a content container
closes #1030
> fix(tabs): addContentContainer property

- projects/cashmere/src/lib/app-switcher/app-switcher-application-link/app-switcher-links.component.html
- projects/cashmere/src/lib/app-switcher/app-switcher-application-link/app-switcher-links.component.scss
- projects/cashmere/src/lib/app-switcher/app-switcher.component.html
- projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
- projects/cashmere/src/lib/app-switcher/app-switcher.component.spec.ts
- projects/cashmere/src/lib/sass/app-switcher.scss
> refactor(app-switcher): convert to mixins

- projects/cashmere/src/lib/banner/hc-banner.component.ts
- projects/cashmere/src/lib/banner/hc-banner.html
- projects/cashmere/src/lib/banner/hc-banner.scss
- projects/cashmere/src/lib/sass/banner.scss
> refactor(banner): convert to mixins

- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.scss
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.scss
- projects/cashmere/src/lib/sass/date-range.scss
> refactor(date-range): convert to mixins

- projects/cashmere/src/lib/sass/navbar.scss
corrects brand img from displaying smaller than expected in Safari
closes #1152
> fix(navbar): safari navbar img fix

- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example-modal.component.html
update example to demo how content can display edge to edge
closes #954
> docs(modal): banner example

- projects/cashmere/src/lib/sass/table.class.scss
> fix(table): fix sort styles

- projects/cashmere-examples/src/lib/checkbox-align/checkbox-align-example.component.html
- projects/cashmere-examples/src/lib/checkbox-align/checkbox-align-example.component.scss
- projects/cashmere-examples/src/lib/checkbox-align/checkbox-align-example.component.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.html
- projects/cashmere/src/lib/checkbox/checkbox.component.scss
- projects/cashmere/src/lib/checkbox/checkbox.component.spec.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.ts
- projects/cashmere/src/lib/sass/checkbox.scss
- src/app/core/document-items.service.ts
adds a parameter to position the checkbox relative to its label
closes #1166
> feat(checkbox): align parameter

- projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.html
- projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.scss
- projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.ts
- projects/cashmere/src/lib/chip/chip.component.html
- projects/cashmere/src/lib/chip/chip.component.scss
- projects/cashmere/src/lib/chip/chip.component.spec.ts
- projects/cashmere/src/lib/sass/chip.scss
support line-wrap on chips
closes #1175
> fix(chips): multiline chips

- projects/cashmere-examples/src/lib/ellipsis-overview/ellipsis-overview-example.component.html
- projects/cashmere-examples/src/lib/popover-overview/popover-overview-example.component.html
- projects/cashmere-examples/src/lib/progress-dots/progress-dots-example.component.html
- projects/cashmere-examples/src/lib/progress-spinner/progress-spinner-example.component.html
- projects/cashmere-examples/src/lib/stepper-overview/stepper-overview-example.component.html
- projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.html
- projects/cashmere/src/lib/select/select.md
Guidance on formatting text in select boxes as per direction from the knowledge development team.  Also corrects select boxes used throughout the site to adhere to these standards.
closes #1178
> docs(select): select text formatting

- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.ts
- projects/cashmere/src/lib/app-switcher/app-switcher.component.ts
corrects logic checking for the current app
closes #1183
> fix(app-switcher): fix current app styles

- projects/cashmere-examples/src/lib/select-disabled/select-disabled-example.component.html
- projects/cashmere-examples/src/lib/select-standard/select-standard-example.component.html
- projects/cashmere-examples/src/lib/select-validation/select-validation-example.component.html
- projects/cashmere-examples/src/lib/select-validation/select-validation-example.component.ts
- projects/cashmere/src/lib/select/select.component.html
allow hc-select to support optgroup markup
closes #1188
> fix(select): support for optgroup

- projects/cashmere-examples/src/lib/input-prefix/input-prefix-example.component.html
- projects/cashmere-examples/src/lib/input-prefix/input-prefix-example.component.ts
- projects/cashmere/src/lib/form-field/hc-form-field.component.ts
- projects/cashmere/src/lib/input/input.directive.ts
> fix(hc-input): allow disabling via FormControl

- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
- projects/cashmere/src/lib/tabs/tab/tab.component.html
- projects/cashmere/src/lib/tabs/tab/tab.component.ts
Inputs queryParams and exactRouteMatch added
Co-Authored-By: Andrew Frueh <andrew-frueh@users.noreply.github.com>
> fix(hc-tab): tab bug fix and enhancements

- projects/cashmere/src/lib/pagination/pagination.component.html
- projects/cashmere/src/lib/pagination/pagination.component.scss
corrected a class misnaming and specificity issue
re #1194
> fix(hc-pagination): fix styles

- projects/cashmere/src/lib/sass/scroll-nav.scss
- projects/cashmere/src/lib/scroll-nav/content/scroll-nav-content.component.scss
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.scss
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.spec.ts
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.ts
> convert scroll nav to mixins

- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.html
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.scss
- projects/cashmere/src/lib/sass/navbar.scss
This one's hard to verify, since the examples don't demonstrate mobile menu functionality. I've tested what I can though.
Fixes #1085
> refactor(navbar): convert mobile menu to mixins

- projects/cashmere/src/lib/stepper/stepper.component.html
- projects/cashmere/src/lib/stepper/stepper.component.ts
> 1220 stepper query params

- projects/cashmere/src/lib/multiselect/multiselect.md
- projects/cashmere/src/lib/sass/_ng-select-theme.scss
1. Add this to usage tab for multiselect:
2. Add theme support for chips with the close icon on the right side instead of left:
> minor patch items for multiselect

- projects/cashmere-examples/src/lib/file-size-overview/file-size-overview-example.component.html
- projects/cashmere-examples/src/lib/file-size-overview/file-size-overview-example.component.ts
- projects/cashmere/src/lib/pipes/file-size/file-size-pipe.md
- projects/cashmere/src/lib/pipes/file-size/file-size-pipe.module.ts
- projects/cashmere/src/lib/pipes/file-size/file-size.pipe.spec.ts
- projects/cashmere/src/lib/pipes/file-size/file-size.pipe.ts
- projects/cashmere/src/lib/pipes/index.ts
- projects/cashmere/src/lib/pipes/pipes.module.ts
- src/app/core/document-items.service.ts
FileSizePipe returns size of file in terms of KB, MB, GB... etc
> feat(file-size.pipe): FileSizePipe returns size of file

- projects/cashmere/src/lib/multiselect/multiselect.md
- projects/cashmere/src/lib/sass/_ng-select-theme.scss
- projects/cashmere/src/lib/sass/_variables.scss
- adds a note about the appendTo property in the usage guide,
- sets z-index on the dropdown that will keep it above a modal it might be nested inside of
> 1257 multiselect dropdown

- projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
- projects/cashmere-examples/src/lib/date-range/date-range-example.component.scss
- projects/cashmere/src/lib/date-range/services/config-store.service.ts
fix issue where the first click on the calendar while input is focused does not register
fix #1271
> fix(date range): fix initial click bug

- projects/cashmere-examples/src/lib/accordion-overview/accordion-overview-example.component.scss
- projects/cashmere-examples/src/lib/accordion-overview/accordion-overview-example.component.ts
- projects/cashmere-examples/src/lib/banner-overview/banner-overview-example.component.html
- projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.module.ts
- projects/cashmere-examples/src/lib/form-field-labels/form-field-labels-example.component.html
- projects/cashmere-examples/src/lib/list-overview/list-overview-example.component.html
- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.module.ts
- projects/cashmere-examples/src/lib/multiselect-overview/multiselect-overview-example.module.ts
- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.module.ts
- projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.html
- projects/cashmere-examples/src/lib/table-sort/table-sort-example.component.scss
- projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.module.ts
- projects/cashmere-examples/src/project-template/package.json
- projects/cashmere-examples/src/project-template/src/styles.scss
- projects/cashmere-examples/src/project-template/stackblitz.md
- projects/cashmere/src/lib/date-range/services/config-store.service.ts
Think I've got all the stackblitz examples working.
Several had broken image links or were missing export statements. Also needed to update the version of the CDK.
re #1209, re #997
> docs(stackblitz): fix examples

- guides/styles/application-launch-screen.md
- src/index.html
thanks for pointing out @joeskeen
> fix(launch screen): fix split second white stripe on launch screen

- guides/styles/about-modal.md
- guides/styles/breadcrumbs.md
- guides/styles/error-pages.md
- guides/styles/login-page.md
- guides/styles/trademarks.md
- projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
- projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.html
- projects/cashmere/src/lib/navbar/navbar.md
- src/app/styles/brand-color/brand-color-demo.component.html
- src/app/styles/brand-color/brand-color-demo.component.ts
- src/app/styles/breadcrumbs/breadcrumbs-style-demo.component.ts
- src/app/styles/chart/chart-demo.component.html
- src/app/styles/chart/chart-demo.component.ts
- src/app/styles/code/code-demo.component.html
- src/app/styles/code/code-demo.component.ts
- src/app/styles/color/color-demo.component.html
- src/app/styles/color/color-demo.component.ts
- src/app/styles/icons/icon-guide.component.html
- src/app/styles/logo/logo-demo.component.html
- src/app/styles/products/products-demo.component.html
- src/app/styles/table/table-demo.component.html
- src/app/styles/table/table-demo.component.ts
- src/app/styles/typography/typography-demo.component.html
Updates recommended spec for standard help menu.
Also updated the "last modified" date for all our style pages while I was in there.  I know those won't always be perfect because they require a manual update and it's easy to forget - but I think it's worth it.  @corykon - actually I think you might need to add that to your Launch Screen style page.
closes #1263
> docs(navbar): add report an issue to help menu

- guides/contribution-guide.md
adds contribution information about commenting code and usage docs
Great suggestion @jacquie to add this.  @isaaclyman - would love your eyes on this new content.  Please feel free to make any edits you'd like.
closes #773
> docs(contribution): code documentation guidelines

- projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.scss
- projects/cashmere/src/lib/drawer/menu-drawer/drawer-item.component.ts
- projects/cashmere/src/lib/drawer/menu-drawer/menu-drawer.component.scss
- projects/cashmere/src/lib/sass/menu-drawer.scss
adds pointer & hover effects to drawer item
@corykon @Br00t4L17y - I made some adjustments the markdown while I was in there to clean things up and allow for the full width hover effect while still having the partial width border.
closes #1143
> style(drawer): menu-drawer css updates

- projects/cashmere-examples/src/lib/ellipsis-overview/ellipsis-overview-example.component.html
- projects/cashmere-examples/src/lib/file-size-overview/file-size-overview-example.component.html
- projects/cashmere-examples/src/lib/null-or-empty-string-overview/null-or-empty-string-overview-example.component.html
- projects/cashmere-examples/src/lib/number-abbreviator-overview/number-abbreviator-overview-example.component.html
- projects/cashmere-examples/src/lib/number-abbreviator-overview/number-abbreviator-overview-example.component.ts
- projects/cashmere-examples/src/project-template/src/styles.scss
- projects/cashmere/src/lib/pipes/index.ts
- projects/cashmere/src/lib/pipes/null-or-empty-string/null-or-empty-string-pipe.md
- projects/cashmere/src/lib/pipes/number-abbreviator/number-abbreviator-pipe.md
- projects/cashmere/src/lib/pipes/number-abbreviator/number-abbreviator-pipe.module.ts
- projects/cashmere/src/lib/pipes/number-abbreviator/number-abbreviator.pipe.spec.ts
- projects/cashmere/src/lib/pipes/number-abbreviator/number-abbreviator.pipe.ts
- projects/cashmere/src/lib/pipes/pipes.module.ts
- src/app/core/document-items.service.ts
- src/styles.scss
Ported over a pipe we use in pop builder. Also tweaked pipe documentation and examples for consistency.
> feat(number abbreviator pipe): added new pipe for abbreviating numbers

- guides/styles/trademarks.md
Requested changes from marketing to the trademarks section of styles
> docs(trademarks): updated trademark standards

- projects/cashmere-examples/src/lib/checkbox-forms/checkbox-forms-example.component.html
- projects/cashmere-examples/src/lib/checkbox-forms/checkbox-forms-example.component.ts
> refactor(checkbox-forms-example): change template driven to reactive

- projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
- projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts
> refactor(datepicker-example): change template driven to reactive

- projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.component.html
- projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.component.ts
- projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.module.ts
> refactor(datepicker-sugar): change template driven to reactive

- guides/styles/trademarks.md
Requested updates from marketing
> docs(trademarks): data science adoption model

- projects/cashmere/src/lib/sass/navbar.scss
Handle icon of any width & no logo.  It's possible to do navbar dropdowns with what we have now, but I'll submit a separate issue to do more thorough support (like make sure a dropdown is supported in the More menu, etc).
closes #1314
> style(navbar): brand & logo updates

- projects/cashmere/src/lib/sass/checkbox.scss
> fix(checkbox): fix dead click zone

- angular.json
- projects/cashmere-examples/src/lib/highlight-overview/highlight-overview-example.component.html
- projects/cashmere-examples/src/lib/highlight-overview/highlight-overview-example.component.ts
- projects/cashmere/src/lib/pipes/highlight/highlight-pipe.md
- projects/cashmere/src/lib/pipes/highlight/highlight-pipe.module.ts
- projects/cashmere/src/lib/pipes/highlight/highlight.pipe.spec.ts
- projects/cashmere/src/lib/pipes/highlight/highlight.pipe.ts
- projects/cashmere/src/lib/pipes/index.ts
- projects/cashmere/src/lib/pipes/pipes.module.ts
- projects/cashmere/src/lib/sass/_typography.scss
- src/app/core/document-items.service.ts
> feat(highlight pipe): added highlight pipe to cashmere

- package-lock.json
- projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.module.ts
- projects/cashmere-examples/src/lib/multiselect-embed-checkbox/multiselect-embed-checkbox-example.component.html
- projects/cashmere/src/lib/date-range/date-range/date-range.directive.spec.ts
- projects/cashmere/src/lib/datepicker/datepicker.component.spec.ts
- projects/cashmere/src/lib/datepicker/datepicker.component.ts
- projects/cashmere/src/lib/datepicker/utils/event-objects.ts
- projects/cashmere/src/lib/radio-button/radio-group.directive.spec.ts
- projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.ts
- projects/cashmere/src/lib/scroll-nav/scroll-nav.module.ts
- projects/cashmere/src/lib/typeform-survey/typeform-survey.component.ts
A collection of the majority of the manual changes I needed to make while upgrading to angular 9 w/ Ivy, to prep us for when it's time to make the actual transition.
> refactor(ivy compatibility): minor changes to prepare for ivy

- projects/cashmere/src/lib/sass/_ng-select-theme.scss
Verified fix in IE11, Chrome, Firefox, and Edge.
> Fix ng-select caret vertical alignment

- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.html
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.spec.ts
- projects/cashmere/src/lib/navbar/navbar-mobile-menu/navbar-mobile-menu.component.ts
- projects/cashmere/src/lib/sass/navbar.scss
> fix(navbar-mobile): fix position bug

- projects/cashmere/src/lib/progress-indicators/progress-dots.component.spec.ts
- projects/cashmere/src/lib/progress-indicators/progress-dots.component.ts
> Progress dots unit test

- projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
> fix(date-range): fix expression changed after checked error

- projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
> fix(am-pm automatic switching): am and pm times switch automatically

- guides/styles/trademarks.md
> docs(trademarks): trademark standards update

- projects/cashmere/src/lib/pop/popover.module.ts
- projects/cashmere/src/lib/pop/tooltip/tooltip.component.scss
- projects/cashmere/src/lib/sass/_cdk-overlay.scss
> fix(tooltip): set explicit line-height

- projects/cashmere/src/lib/app-switcher/app-switcher.component.spec.ts
- projects/cashmere/src/lib/app-switcher/app-switcher.component.ts
Retry error message will now disappear after success rather than stick around
closes #1382
> fix(app-switcher): error message

- projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
Allows user to specify horizontalAlign and verticalAlign
properties for the hcTooltip to position the hcTooltip.
closes #1396
> refactor(hctooltip): horizontalAlign verticalAlign hcTooltip

- projects/cashmere/src/lib/navbar/navbar.component.spec.ts
- projects/cashmere/src/lib/navbar/navbar.component.ts
allows the more menu to work even if window is opened in mobile state
closes #1399
> fix(navbar): more menu widths calc fix

- projects/cashmere-examples/tsconfig.lib.json
- projects/cashmere/src/lib/banner/hc-banner.component.spec.ts
- projects/cashmere/src/lib/banner/hc-banner.component.ts
- projects/cashmere/src/lib/banner/hc-banner.html
- projects/cashmere/tsconfig.lib.json
added a hc-banner.component.ts unit test file.
added enum for the type of banner for better developer experience.
closes #1305
> test(hc-banner): added unit test

- guides/using-cashmere-bits.md
- projects/cashmere-examples/src/lib/change-case-pipe-overview/change-case-pipe-overview-example.component.html
- projects/cashmere-examples/src/lib/change-case-pipe-overview/change-case-pipe-overview-example.component.ts
- projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.html
- projects/cashmere/src/lib/chip/chip.component.html
- projects/cashmere/src/lib/chip/chip.component.scss
- projects/cashmere/src/lib/chip/chip.component.ts
- projects/cashmere/src/lib/sass/chip.scss
- src/app/components/component-viewer/component-viewer.component.html
- src/app/components/components.component.html
- src/app/components/components.component.scss
- src/app/components/components.component.ts
- src/app/core/cashmere-bits-document-items.json
- src/app/core/document-items.schema.json
- src/app/core/document-items.service.ts
- src/app/guides/guides.service.ts
- src/styles.scss
Also fixed a few docs bugs I found along the way.
> Add documentation for using Cashmere Bits

- projects/cashmere-examples/src/lib/tile-overview/tile-overview-example.component.html
- projects/cashmere-examples/src/lib/tile-overview/tile-overview-example.component.scss
- projects/cashmere-examples/src/lib/tile-overview/tile-overview-example.component.ts
- projects/cashmere/src/lib/banner/hc-banner.component.spec.ts
- projects/cashmere/src/lib/sass/tile.scss
- projects/cashmere/src/lib/tile/index.ts
- projects/cashmere/src/lib/tile/tile-header.directive.spec.ts
- projects/cashmere/src/lib/tile/tile-header.directive.ts
- projects/cashmere/src/lib/tile/tile.component.spec.ts
- projects/cashmere/src/lib/tile/tile.md
- projects/cashmere/src/lib/tile/tile.module.ts
- src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.html
- src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.scss
- src/app/core/cashmere-components-document-items.json
@corykon & @jonest - let me know what you think about this update.  Ty suggested this a while back, because there are common styles we use for tile headers that aren't really baked into Cashmere anywhere for devs to easily leverage.  I added two styles that I use regularly for tile headers, but if you have others, please let me know and I'll add them.
@joeskeen - let me know if I did the unit test right :-)
closes #1144
closes #1307
> Tile header

- projects/cashmere/src/lib/sass/_ng-select-theme.scss
> fix(ng-select theme): fix missing padding

- projects/cashmere/src/lib/modal/modal.service.ts
only increment if multiple modals are allowed; don't count up forever
closes #1426
> fix(modal): zIndex incrementing

- projects/cashmere-examples/src/lib/popover-overview/popover-overview-example.component.html
- projects/cashmere-examples/src/lib/popover-overview/popover-overview-example.component.ts
- projects/cashmere-examples/src/lib/tooltip-overview/tooltip-overview-example.component.html
- projects/cashmere-examples/src/lib/tooltip-overview/tooltip-overview-example.component.ts
- projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
- projects/cashmere/src/lib/pop/popover-anchoring.service.ts
- projects/cashmere/src/lib/pop/popover.component.html
- projects/cashmere/src/lib/pop/popover.component.ts
- projects/cashmere/src/lib/pop/tooltip/tooltip.component.html
- projects/cashmere/src/lib/pop/tooltip/tooltip.component.scss
- projects/cashmere/src/lib/pop/tooltip/tooltip.component.ts
adds maxWidth parameter & fixes positioning for large tooltips
closes #1427
> feat(pop): maxWidth parameter

- projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
Add restoreFocus property
closes #1401
> feat(hctooltip): restoreFocus hcTooltip

- projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.html
- projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.scss
- projects/cashmere/src/lib/drawer/drawer.component.ts
> fix(drawer): add ignoreEscapeKey property

- projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
- projects/cashmere/src/lib/table/cell.ts
fixes bugs in `hc-table` and `hcPop`
> fix(cashmere): 9.0.0 release bugs

- projects/cashmere/src/lib/sass/pagination.scss
corrects colliding styles from primary-button
closes #1464
> fix(pagination): disabled hover styles

- projects/cashmere/src/lib/util.ts
add check for null to parseBooleanAttribute
closes #1474
> fix(utils.ts): parseBooleanAttribute fix

- guides/content/trademarks.md
Updated capitalization and added a no longer in use section.
> docs(trademarks): update caps

- guides/getting-started.md
- projects/cashmere/src/lib/icon-font/hcicons.scss
corrected getting started and stylesheet fix
> fix(hcicons): hc-icons import

- projects/cashmere/src/lib/icon-font/css/hcicons.css
- projects/cashmere/src/lib/icon-font/hcicons.css
- src/app/foundations/icons/icon-guide.component.html
include css file for font in addition to existing scss file
> fix(hc-icons): add css file

- projects/cashmere/src/lib/pagination/pagination.component.html
- projects/cashmere/src/lib/pagination/pagination.component.spec.ts
- projects/cashmere/src/lib/pagination/pagination.component.ts
- projects/cashmere/src/lib/pagination/pagination.module.ts
fixes bug where programatically changing pageSize didn't update select
closes #1533
> fix(pagination): pageSize select update fix

- guides/styles/error.md
- projects/cashmere-examples/ng-package.json
- projects/cashmere-examples/ng-package.prod.json
- projects/cashmere-examples/src/project-template/package.json
- src/app/components/component-viewer/component-viewer.component.html
- src/app/content/content.module.ts
- src/app/content/personas/persona-list/persona-list.component.html
- src/app/content/personas/persona-org/persona-org.component.html
- src/app/content/usage/usage-list/usage-list.component.html
- src/app/content/usage/usage-list/usage-list.component.scss
- src/app/foundations/brand-colors/brand-color-demo.component.html
- src/app/foundations/code/code-demo.component.html
- src/app/foundations/color/color-demo.component.html
- src/app/foundations/fonts/fonts-demo.component.html
- src/app/foundations/icons/icon-guide.component.html
- src/app/foundations/logo/logo-demo.component.html
- src/app/foundations/products/products-demo.component.html
- src/app/foundations/typography/typography-demo.component.html
- src/app/guides/guide/guide.component.html
- src/app/shared/feedback-form/feedback-form.component.html
- src/app/shared/feedback-form/feedback-form.component.scss
- src/app/shared/feedback-form/feedback-form.component.ts
- src/app/shared/markdown-content.component.ts
- src/app/shared/shared.module.ts
- src/app/styles/about/about-modal.component.html
- src/app/styles/table/table-demo.component.html
adds page feedback form to all pages
_note_ - the `lodash` addition is just a Stackblitz fix where a package wasn't getting loaded by default on our Stackblitz examples.  I'm sneaking it into this PR.
closes #1422
> docs(feedback-form): page feedback form

- projects/cashmere-examples/src/lib/multiselect-custom-templates/multiselect-custom-templates-example.component.scss
> docs(ng-select example): fix selected styles

- guides/contribution-guide.md
- package.json
Enable cashmere to run locally with BrowserStack.
> feat(package.json): run browserstack locally

- guides/content/references.md
- src/app/content/content-routes.module.ts
add new references usage page to content section
> docs(content): new content page

- projects/cashmere/src/lib/sass/modal.scss
re #1538
Modals will take up the full screen width and height when opened in a small browser (excluding small modals)
> feat(modal): responsive full screen modal

- src/styles.scss
docs are no longer cut off when viewed on cashmere mobile
closes #1583
> fix(api docs): fixed the issue with docs being cutoff

- projects/cashmere/src/lib/sass/button-toggle.scss
closes #1573
Old Colors:
New Colors:
> fix(button toggle): darkened the color of the toggle button

- guides/creating-new-components.md
- src/app/guides/guides.service.ts
this guide show two different ways to create a new component
fix #1442
> feat(create component): how to create a new component

- projects/cashmere/src/lib/drawer/drawer-container.component.ts
- projects/cashmere/src/lib/navbar/navbar.component.html
- projects/cashmere/src/lib/sass/navbar.scss
- src/styles.scss
Moved the hamburger icon to the left, left-aligned the title, and expanded the ability for right-content
to show on tablets and larger mobile devices
closes #1581
closes #1566 
Before:
After (iPhone): 
(iPad):
> fix(mobile navbar): adjusted the ux for the mobile navbar

- projects/cashmere/src/lib/picklist/pane/pick-pane.component.html
the select all button no longer submits the response right away
closes #1605
> fix(picklist btn): fixes submit btn issue

- projects/cashmere/src/lib/date-range/services/calendar-overlay.service.ts
change the center property, instead of being default to false now is an optional parameter
closes #1618
> fix(data range): optional parameter

- projects/cashmere/src/lib/modal/modal-options.ts
- projects/cashmere/src/lib/modal/modal-window.component.scss
- projects/cashmere/src/lib/modal/modal-window.component.ts
- projects/cashmere/src/lib/modal/modal.service.ts
- projects/cashmere/src/lib/modal/modal.ts
- projects/cashmere/src/lib/sass/modal.class.scss
- projects/cashmere/src/lib/sass/modal.scss
When setting the 'disableFullScreen' property to true, the modal will no longer display in
full-screen on mobile
addresses #1578
> feat(modal): disable full screen on mobile

- projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
> fix(datepicker): fixed the minutes max/min

- projects/cashmere/src/lib/sass/sort.scss
Fixes https://github.com/HealthCatalyst/Fabric.Cashmere/issues/1635
> fix(sort): make sort icon consistent size

- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example-modal.component.html
- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.component.html
- projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.component.ts
- projects/cashmere/src/lib/modal/modal-options.ts
- projects/cashmere/src/lib/modal/modal-window.component.scss
- projects/cashmere/src/lib/modal/modal-window.component.spec.ts
- projects/cashmere/src/lib/modal/modal-window.component.ts
- projects/cashmere/src/lib/modal/modal.component.ts
- projects/cashmere/src/lib/modal/modal.service.spec.ts
- projects/cashmere/src/lib/modal/modal.service.ts
- projects/cashmere/src/lib/modal/modal.ts
- projects/cashmere/src/lib/sass/modal.scss
adds resizable functionality to modals that works with draggable
closes #647
> feat(modal): resizable modals

- projects/cashmere/src/lib/modal/active-modal.ts
_pretty_ sure this should fix the annoyance that Mark and Brad have run into
> fix(modal): don't force implementers to type modals

- src/app/foundations/products/products-demo.component.html
updates product names on product logos, adds new products
> docs(product logos): update names

- projects/cashmere/src/lib/sass/_code-highlight.scss
- projects/cashmere/src/lib/sass/_typography.scss
> fix(code block styles): fix styles for highlighting code blocks

- package-lock.json
- package.json
- projects/cashmere-examples/src/project-template/package.json
- projects/cashmere/package.json
updates package to remove woff2 errors
closes #1672
> fix(noto-sans): updated NPM package

- projects/cashmere/src/lib/radio-button/radio.ts
corrects the value emitted by the change event on radio groups
closes #1658
> fix(radio-button): radio group change fix

- projects/cashmere/src/lib/modal/modal-window.component.scss
- projects/cashmere/src/lib/modal/modal.service.ts
- projects/cashmere/src/lib/sass/modal.scss
fixes / simplifies styles for responsive modals
closes #1678
> fix(modal): corrected responsive styles

- projects/cashmere/src/lib/navbar/navbar-link/navbar-link.component.ts
allow the active property to accept string as well as boolean values
> fix(navbar): active supports strings

- projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
allows tooltips to set a maxWidth
closes #1753
> fix(popover): width constrained tooltips

- package.json
Enable production mode for the Cashmere user-guide project.
> docs(build:user): enable prod mode on user-guide

- projects/cashmere/src/lib/toaster/hc-toast-options.ts
- projects/cashmere/src/lib/toaster/hc-toast.component.html
- projects/cashmere/src/lib/toaster/hc-toast.component.ts
- projects/cashmere/src/lib/toaster/hc-toaster.service.ts
allow a function to be called when a toast is clicked
closes #1756
> feat(toasts): toastClicked option

- src/app/app.component.html
- src/app/components/components.component.html
- src/app/guides/guides.component.html
- src/app/mobile/mobile.component.html
- src/app/shared/base-demo.component.scss
- src/app/styles/styles.component.html
- src/styles.scss
> docs(web apps): add subtitles

- projects/cashmere/src/lib/date-range/date-range/date-range.directive.spec.ts
- projects/cashmere/src/lib/date-range/date-range/date-range.directive.ts
- projects/cashmere/src/lib/date-range/index.ts
- projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
- projects/cashmere/src/lib/date-range/services/calendar-overlay.service.ts
- projects/cashmere/src/lib/date-range/services/config-store.service.ts
adds closed emitter to fire when picker is dismissed or saved
closes #1776
> feat(date-range): closed emitter

- src/app/content/usage/usage-list/usage-list.component.scss
fix css for ul li across browsers
> docs(styling): bulleted li

- src/app/content/usage/usage-list/usage-list.component.html
- src/app/content/usage/usage-list/usage-list.component.ts
- src/app/content/usage/usage.component.html
edit the Overview text and add icon button to clear search box
> docs(edits): overview text

- guides/supported-browsers.md
- projects/cashmere/src/lib/sass/_typography.scss
re #1786
Will revisit with the release of Cashmere v13. Made a note on that issue #1714.
> docs(browser support): add note on plans for IE 11

- guides/content/trademarks.md
Changed data science adoption model to Healthcare.AI Framework and added Touchstone Match under unregistered marks.
> docs(trademarks):quarterly updates

- src/app/styles/ie-support/ie-support.component.html
fixed some minor things after trying out the messaging in pop analyzer
> docs(ie support guide): better styles and instructions

- projects/cashmere/package.json
> build(deps): update guidance on core-js to allow for newer versions

- projects/cashmere-examples/src/lib/radio-button-align/radio-button-align-example.component.html
- projects/cashmere-examples/src/lib/radio-button-align/radio-button-align-example.component.scss
- projects/cashmere-examples/src/lib/radio-button-align/radio-button-align-example.component.ts
- projects/cashmere/src/lib/radio-button/radio-button.component.html
- projects/cashmere/src/lib/radio-button/radio-button.component.scss
- projects/cashmere/src/lib/radio-button/radio.ts
- projects/cashmere/src/lib/sass/radio-button.scss
- src/app/core/cashmere-components-document-items.json
adds ability to center radio label to top, center, or bottom; also fixes a style bug on tight radio buttons
closes #1811
closes #1810
> feat(radio): radio align param

- src/app/styles/ie-support/ie-support.component.html
- src/app/styles/table/table-demo.component.html
Couple minor documentation changes that devs have pointed out to me as needed.
> 1840 docs fixes

- guides/styles/launch-screen.md
add an alternate minimalist version of the loading screen
closes #1853
> docs(launch-screen): light version

- projects/cashmere/src/lib/sass/navbar.scss
Increased the line-height in navbar. 
closes #1843
> Navbar CSS Fix

- src/app/analytics/template/analytics-template.component.html
- src/app/analytics/template/analytics-template.component.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/content/usage/usage-list/usage-list.component.ts
- src/app/home/home.component.ts
- src/app/search-results/search-results.component.html
- src/app/search-results/search-results.component.ts
- src/app/shared/application-insights/application-insights.service.ts
additional tracking hooks for site search
> docs(search): additional app insights tracking

- src/app/shared/feedback-form/feedback-form.component.ts
remove google sheets integration on feedback form (using app insights)
closes #1834
> docs(feedback-form): remove google sheets

- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.html
- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.scss
- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.ts
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.html
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
Cherry-picking the tab updates into master before we do the big 13 release
> Cashmere 12.7.3

- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
@bskeen I'm cherry-picking this into master so you can get a release before we push the Angular 13 update
> fix(tab-set): fix tab rendering

- projects/cashmere/src/lib/sass/slide-toggle.scss
Thanks for the suggestion on this @corykon
> fix(slide-toggle): fixed scss calculation

- guides/getting-started.md
- guides/styles/login.md
- projects/cashmere-examples/src/project-template/src/styles.scss
- projects/cashmere/package.json
- projects/cashmere/src/lib/multiselect/multiselect.md
Update to the library exports to make sure we can import cashmere styles without absolute paths. Updated the docs to match.
> 1905 package exports

- projects/cashmere-examples/src/lib/instance-switcher-overview/instance-switcher-overview-example.component.html
- projects/cashmere-examples/src/lib/instance-switcher-overview/instance-switcher-overview-example.component.ts
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.html
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.scss
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.ts
- projects/cashmere/src/lib/instance-switcher/instance-switcher.module.ts
- projects/cashmere/src/lib/measurable/measurable.component.ts
- projects/cashmere/src/lib/sass/instance-switcher.scss
update the instance switcher so each instance is editable on a double click or context menu
> feat(instance-switcher): make instance switcher editable

- package-lock.json
- package.json
- src/app/shared/highlight/highlight.directive.ts
> docs(highlight): update highlight.js syntax

- projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.html
- projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.scss
- projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.ts
- projects/cashmere/src/lib/sass/search-bar.scss
- projects/cashmere/src/lib/search-bar/search-bar.component.html
- projects/cashmere/src/lib/search-bar/search-bar.component.scss
- projects/cashmere/src/lib/search-bar/search-bar.component.ts
> feat(search-bar): add input styles

- projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.html
- projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.scss
- projects/cashmere-examples/src/lib/measurable-vertical/measurable-vertical-example.component.html
- projects/cashmere-examples/src/lib/measurable-vertical/measurable-vertical-example.component.scss
- projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.html
- projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.ts
- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.html
- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.scss
- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.ts
- projects/cashmere-examples/src/lib/tabs-vertical/tabs-vertical-example.component.html
- projects/cashmere-examples/src/lib/tabs-vertical/tabs-vertical-example.component.ts
- projects/cashmere-examples/src/lib/tile-overview/tile-overview-example.component.html
- projects/cashmere-examples/src/lib/tile-overview/tile-overview-example.component.ts
- projects/cashmere/src/lib/navbar/navbar.component.ts
- projects/cashmere/src/lib/sass/tab.scss
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.html
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.scss
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.spec.ts
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
- projects/cashmere/src/lib/tabs/tab/tab.component.html
- projects/cashmere/src/lib/tabs/tab/tab.component.ts
- projects/cashmere/src/lib/tabs/tabs.module.ts
Huge thanks again @HaydenDalley35 for the suggestion and code examples on this one.  It's a massive improvement to the Tabs component - one of the very first Cashmere components.
This is a pretty big PR, and admittedly I snuck in a few fixes to things that aren't related to tabs.  So to make your lives easier, I'll schedule a 30 min call for early next week to walk you through what I did here.  And hopefully that'll make reviewing easier.  Thanks!
closes #1880
> Tabs more menu

- README.md
- projects/cashmere/README.md
needing to trigger a release for testing, and updating readme files while at it
> fix(readme): update readme files  and trigger a library release

- projects/cashmere-examples/src/lib/radio-button-standard/radio-button-standard-example.component.html
- projects/cashmere-examples/src/lib/radio-button-standard/radio-button-standard-example.component.scss
- projects/cashmere-examples/src/lib/radio-button-standard/radio-button-standard-example.component.ts
- projects/cashmere/src/lib/input/input.directive.ts
- projects/cashmere/src/lib/radio-button/radio.ts
allows radio buttons to include input elements
closes #1933
> fix(radio): support child inputs

- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.html
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
> fix(tabs): allow for no overflow controls

- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
> fix(tabs): make sure selected tab is always shown

- projects/cashmere/src/lib/form-field/hc-form-field.component.ts
mobile styling was not applied when added initially
closes #1949
> fix(input): mobile style init

- projects/cashmere-examples/src/lib/instance-switcher-overview/instance-switcher-overview-example.component.html
- projects/cashmere-examples/src/lib/instance-switcher-overview/instance-switcher-overview-example.component.scss
- projects/cashmere-examples/src/lib/instance-switcher-overview/instance-switcher-overview-example.component.ts
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.html
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.scss
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.ts
Update instance switcher to allow for maxWidth or fit content.
Also will default to the prior name if the new name entered is blank.
Closes #1959
> feat(instance switcher): add length/no entry

- projects/cashmere-examples/src/lib/instance-switcher-overview/instance-switcher-overview-example.component.ts
- projects/cashmere/src/lib/instance-switcher/instance-switcher-interfaces.ts
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.html
- projects/cashmere/src/lib/instance-switcher/instance-switcher.component.ts
Add individual tool tips for the instance switcher
closes #1973
> fix(instanceswitcher): individual tool tip

- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.html
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
I added handling of the mouse wheel to the tabs in a tab set
feat 1971
> feat(tab-set): add scroll to tab set

- guides/content/trademarks.md
Updated trademark info based on quarterly trademark review meeting.
@kadchrist - just putting your changes into a different PR.  The formatting on the first line of the commit message needs to look like this or the app compiler will get messed up when it builds:
`docs(trademarks): q4 trademarks update`
and the second line can be whatever you want
> docs(trademarks): q4 trademarks update

- projects/cashmere-examples/src/lib/selected-tab-input/selected-tab-input-example.component.html
- projects/cashmere-examples/src/lib/selected-tab-input/selected-tab-input-example.component.scss
- projects/cashmere-examples/src/lib/selected-tab-input/selected-tab-input-example.component.ts
- projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
- src/app/core/cashmere-components-document-items.json
I fixed a couple of issues with the selectedTab input causing it to break on component init
> fix(tab-set): fix selectedTab input

- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.html
- projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.ts
- projects/cashmere/src/lib/tabs/tab/tab.component.ts
Hey @juanslinger - fortunately this one was an easy fix.  I updated the Horizontal Tabs example slightly to demo the updated functionality.  Let me know if the change looks good to you.
...and as promised, $5 motivosity coming your way for finding a tabs bug/fix to add to the next release!  Thank you!!
closes #2044
> fix(tabs): tabClickHandler should emit Event

- guides/content/trademarks.md
Submitting on behalf of @kadchrist.
> docs(trademarks): feb 22 update

- projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.component.html
- projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.component.ts
- projects/cashmere/src/lib/checkbox/checkbox.component.ts
> fix(checkbox): set touched on click

- projects/cashmere-examples/src/lib/file-uploader-overview/file-uploader-overview-example.component.html
- projects/cashmere-examples/src/lib/file-uploader-overview/file-uploader-overview-example.component.scss
- projects/cashmere-examples/src/lib/file-uploader-overview/file-uploader-overview-example.component.ts
- projects/cashmere/src/lib/file-uploader/file-uploader.component.html
- projects/cashmere/src/lib/file-uploader/file-uploader.component.ts
corrects error on FileList reset
Nice troubleshooting @isaaclyman - your fix worked great.  Needed to change a little bit of logic on the template to accommodate, but all looks good.  Updated the example as well to demo the functionality.
closes #2078
> fix(file-uploader): reset function fix

- projects/cashmere-examples/src/lib/file-uploader-overview/file-uploader-overview-example.component.html
- projects/cashmere-examples/src/lib/file-uploader-overview/file-uploader-overview-example.component.scss
- projects/cashmere-examples/src/lib/file-uploader-overview/file-uploader-overview-example.component.ts
- projects/cashmere/src/lib/file-uploader/file-uploader.component.html
- projects/cashmere/src/lib/file-uploader/file-uploader.component.ts
corrects error on FileList reset
closes #2078
> Cashmere 13.8.2

- projects/cashmere/src/lib/button-toggle/button-toggle.component.ts
fix removing disabled style after turning off disabled
closes #2087
> fix(button-toggle): disabled style fix

- projects/cashmere-examples/src/project-template/angular.json
> docs(stackblitz): importing cashmere styles

- projects/cashmere/src/lib/sass/sidenav.scss
- projects/cashmere/src/lib/sidenav/sidenav.component.html
- projects/cashmere/src/lib/sidenav/sidenav.component.scss
- projects/cashmere/src/lib/sidenav/sidenav.component.ts
finding more little things to tweak on sidenav
> fix(sidenav): fix active tab styles and add keyboard accessibility

- projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.scss
- projects/cashmere-examples/src/lib/drawer-overlay/drawer-overlay-example.component.scss
- projects/cashmere-examples/src/lib/drawer-side/drawer-side-example.component.scss
- projects/cashmere/src/lib/drawer/drawer.component.ts
- projects/cashmere/src/lib/drawer/menu-drawer/menu-drawer.component.ts
- projects/cashmere/src/lib/pop/popover-accessibility.service.ts
- projects/cashmere/src/lib/sass/drawer.scss
- projects/cashmere/src/lib/sass/sidenav.scss
quicker animations, lighter shadows, padding in examples
@andrew-frueh let me know how you feel about these (esp animation speed and shadows). This is what I'm doing in platform apps these days.
re #2028
> fix(drawer): refresh styles

- src/app/analytics/template/analytics-template.component.html
- src/app/analytics/template/analytics-template.component.scss
- src/app/analytics/template/analytics-template.component.ts
- src/assets/analytics/powerbi-template.json
- src/assets/analytics/qlik-template.json
- src/assets/analytics/tableau-template.json
> Powerbi template v2

- guides/accessibility/overview.md
- src/app/accessibility/accessibility-routes.module.ts
- src/app/accessibility/accessibility.component.html
- src/app/accessibility/accessibility.component.ts
- src/app/accessibility/accessibility.module.ts
- src/app/app.component.html
- src/app/app.module.ts
Create a new section for accessibility documentation and add an overview document.
> docs(accessibility): add accessibility documentation

- guides/accessibility/ux-writing.md
- src/app/accessibility/accessibility-routes.module.ts
- src/app/accessibility/accessibility.component.html
- src/app/accessibility/accessibility.component.ts
- src/app/app.component.html
- src/app/content/content-routes.module.ts
This commit contains two changes:
* Moves Accessibility content into its own top-level section
* Moves Ux Writing Accessibility content into the Accessibility section
> docs(accessibility): build out accessibility content

- projects/cashmere/src/lib/checkbox/checkbox.component.ts
- projects/cashmere/src/lib/file-uploader/file-uploader.component.ts
- projects/cashmere/src/lib/input/input.directive.ts
- projects/cashmere/src/lib/radio-button/radio.ts
- projects/cashmere/src/lib/select/select.component.ts
- projects/cashmere/src/lib/slide-toggle/slide-toggle.component.ts
detect changes for form control validation
> fix(form-fields): change detection

- projects/cashmere-examples/src/lib/input-required/input-required-example.component.html
- projects/cashmere-examples/src/lib/input-required/input-required-example.component.scss
- projects/cashmere-examples/src/lib/input-required/input-required-example.component.ts
- projects/cashmere/src/lib/input/input.directive.ts
adds support for validation on change
closes #2183
> feat(input): validation type

- projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.html
- projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.ts
- projects/cashmere/src/lib/sass/search-bar.scss
- projects/cashmere/src/lib/search-bar/search-bar.component.html
- projects/cashmere/src/lib/search-bar/search-bar.component.ts
> feat(searchbar): ability to trigger search on icon click

- src/app/content/usage/usage-list/usage-list.component.ts
replace google app script link to point to correct google sheet
> docs(content): update link to google app script

- projects/cashmere/src/lib/sidenav/sidenav.component.html
avoids an "undefined" tooltip
fix #2232
> fix(sidenav): handle empty description property

- guides/contribution-guide.md
- src/app/home/home.component.html
* Adds a banner to the home page that directs visitors to the Contribution Guide to make it easier to find.
* Embeds my screencast under the "Setup Environment" section
> docs(contributions): add home banner and video embed

- projects/cashmere/src/lib/sass/navbar.scss
corrects mobile menu icon widths
closes #2237
> fix(navbar): mobile menu icons

- projects/cashmere-examples/src/lib/input-required/input-required-example.component.html
- projects/cashmere/src/lib/input/input.directive.ts
> fix(input directive): fix - error not resetting when validation=change

- src/app/shared/application-insights/application-insights.service.ts
- src/app/shared/feedback-form/feedback-form.component.ts
Feedback form data now will be stored in the Product Catalog database and a notification will be pushed to Slack whenever a form is submitted (on the `hc-docs-feedback` channel)
> docs(feedback): updated feedback submit endpoint

- projects/cashmere-examples/src/lib/progress-bar/progress-bar-example.component.html
- projects/cashmere-examples/src/lib/progress-bar/progress-bar-example.component.scss
- projects/cashmere-examples/src/lib/progress-bar/progress-bar-example.component.ts
- projects/cashmere-examples/src/lib/progress-spinner/progress-spinner-example.component.html
- projects/cashmere/src/lib/progress-indicators/index.ts
- projects/cashmere/src/lib/progress-indicators/progress-bar.component.html
- projects/cashmere/src/lib/progress-indicators/progress-bar.component.spec.ts
- projects/cashmere/src/lib/progress-indicators/progress-bar.component.ts
- projects/cashmere/src/lib/progress-indicators/progress-indicators.module.ts
- projects/cashmere/src/lib/sass/cashmere.scss
- projects/cashmere/src/lib/sass/progress-bar.scss
- projects/cashmere/src/lib/sass/progress-spinner.scss
- src/app/core/cashmere-components-document-items.json
adds progress bar component to progress indicators module
closes #2295
> feat(progress-indicators): progress bar component

- projects/cashmere/src/lib/table/table.component.ts
correct null injector error on table component introduced in the move to Angular 17
> fix(table): angular 17 null injector error

- projects/cashmere/src/lib/toaster/hc-toast.component.scss
> fix(toast): better line heights

- projects/cashmere/src/lib/modal/modal-window.component.ts
- projects/cashmere/src/lib/toaster/toaster.md
- re #2127 
- clean up some toasty docs
> Minor bugs

- projects/cashmere-examples/src/lib/release-notes-modal/release-notes-modal-example.component.ts
- projects/cashmere/src/lib/accordion/accordion.component.ts
- projects/cashmere/src/lib/modal/modal-body.component.ts
- projects/cashmere/src/lib/release-notes-modal/release-notes-modal.component.html
- projects/cashmere/src/lib/release-notes-modal/release-notes-modal.component.scss
- projects/cashmere/src/lib/release-notes-modal/release-notes-modal.component.ts
- projects/cashmere/src/lib/sass/release-notes.scss
smoothed out styles for headers, tables, other elements. opened accordion scrolls to top of viewport
re #2392
> feat(release notes modal): minor ux enhancements
