HealthCatalyst/Fabric.Cashmere

package-lock.json
package.json

There seems to be an issue with the package-lock file from pull request #10 where I did not commit a dependency that's needed. This resolved the issue I was experiencing where I deleted node_modules and ran 
```
npm install && npm run lint
```
but was getting "cannot find module tsutils"

Fixes a dependency issue with tsutils and tslint

---

src/app/demo/demo.module.ts
src/app/lib/cashmere.ts
src/app/lib/checkbox/checkbox-demo/checkbox-demo.component.html
src/app/lib/checkbox/checkbox-demo/checkbox-demo.component.ts
src/app/lib/checkbox/checkbox.component.html
src/app/lib/checkbox/checkbox.component.scss
src/app/lib/checkbox/checkbox.component.ts
src/app/lib/checkbox/index.ts

Updated checkbox so that it is compatible with angular's reactive and template forms. Added support for more of the input element's native attributes and properties. I didn't mess with any of the component's styles. The alterations to the css is a format change, and I don't know why tslint seems to be letting these differences get through. This is purely a functional update

Checkbox better support for angular forms and native properties

---

docs/index.html

Update pre-bootloader for document app to handle svg-related issue where svgs don't properly display as a background-image css style in IE.

Fix IE svg issue in bootloader

---

docs/app/demo/accordion/accordion-demo.component.html
docs/app/demo/accordion/accordion-demo.component.ts
docs/app/demo/demo-routes.ts
docs/app/demo/demo.module.ts
docs/app/demo/side-nav/side-nav.component.html
lib/public_api.ts
lib/src/accordion/accordion-toolbar.component.ts
lib/src/accordion/accordion.component.html
lib/src/accordion/accordion.component.scss
lib/src/accordion/accordion.component.ts
lib/src/accordion/accordion.module.ts
lib/src/accordion/index.ts

For now I've left the styling very bare. This component allows you to have an accordion which expands/contracts a section in the DOM. There are properties that allow you to change the location of the trigger button and if you wish you could hide the toolbar at the top completely and toggle the accordion with a button anywhere on the DOM styled as you want.
In the future, if others would find it useful, I will add a parent component which controls sibling accordions so that when one accordion is expanded the others are closed, so you only have one accordion in focus at one time
Closes #99

Adds Accordion component

---

docs/app/home/home.component.html

I yanked this out in a previous PR without explaining, and I saw it find it's way back in - but since I removed the CSS too it's messing up the home page.  The reason I pull out the footer is because I'd like to wrap the content it contained into an About Modal as soon as we get #107 added - nudge, nudge @joeskeen :-P
That way will be more consistent with where other Catalyst apps store version info, etc.  And we want Cashmere's demo site to be a model for other apps.  So that's why I pulled the footer out.

Remove footer from home page

---

docs/app/components/tabs/tabs-demo.component.scss
lib/src/tabs/tab-set.component.scss
lib/src/tabs/tab-set.component.ts

Resolves #137.  @corytak - I think/hope this is a complete fix.  It's kind of a mix between your approach and my old approach, with one extra bit mixed in.  I went back to `display: table` to avoid the overflow issue I mentioned - but it wouldn't work properly without the body height you added today.  The one additional piece I added was a container div to the component template that applies a different style if it's a horizontal or vertical tab set.

Tab height fix

---

docs/app/components/typeform-survey/typeform-survey-demo.component.html
lib/src/tabs/tab-set.component.ts

Noticed I forgot to change the typeform demo component to be `tabTitle` on the demo so the tab's were missing. I also implemented @corykon 's suggestion to remove a method.

Fix missing tab title bug; make @corykon's suggestion

---

lib/src/tabs/tab-set.component.scss

Really minor change, but I just noticed this when we added the Typeform component.  When the vertical tab list is longer than the content, if you select the last component, the highlighted state is flush with the bottom of the page, which looks a little odd.  Just like at the top of the tab list, it's better if we have a small white buffer so it looks more like this:

Vertical Tab Padding Adjustment

---

docs/app/components/components-routes.ts
docs/app/components/components.component.html
docs/app/components/components.component.ts
docs/app/components/typeform-survey/typeform-survey-demo.component.html
docs/app/styles/styles.component.html
docs/app/styles/styles.component.ts
docs/styles.scss

Realized after Cory's recent Typeform component addition that the responsive select navigation menu was still hard-coded.  Following the updates we made to make use of the router config for navigation, I'm now populating that select component dynamically the same way.  So when a new component is added to the routes, as long as it includes the data element, "title", it will get pulled into the responsive menu.
Also pinned the responsive subnav under the main navbar, because I found that it was annoying when viewing on a phone to have to scroll up to navigate.
And last, updated the content of the Typeform survey component overview as per a conversation Cory and I had with the Customer Feedback team.  Ultimately I think the recommendations I added for the survey prompt will make more sense …

Dynamic Responsive Select Menu

---

docs/app/styles/code/code-demo.component.html
docs/app/styles/code/code-demo.component.ts
docs/app/styles/styles-routes.ts
docs/app/styles/styles.component.html
docs/app/styles/styles.component.ts
docs/app/styles/styles.module.ts
docs/app/styles/typography/typography-demo.component.html
docs/styles.scss
guides/styles/code.md
lib/src/sass/_typography.scss

Resolves #119.  Splits the two code elements out from the Typography section and adds additional information around syntax highlighting.  @cedar-ave - let me know if you'd suggest any additional content or guidelines in this section.

"Code Display" - Styles section

---

package-lock.json
package.json

This should fix the vulnerability notification we've been getting. types/moment was listed as a devDependency in package.json but It wasn't being used anywhere.

remove types/moment

---

.gitignore
lib/build.js
lib/package-lock.json
lib/package.json
package-lock.json

I was trying to add Fabric.Cashmere to the Fabric.Authorization.AccessControl demo project.  When trying to import the Cashmere SASS styles, it caused an error.  Looking into it, I realized that the cashmere.sass file was just importing other SASS files, which were not included in the package when built for NPM.  This fixes the issue, copying all SASS styles into the NPM package directory when the package is built.

Include all SASS stylesheets in the package so they can be used in consuming applications

---

lib/src/drawer/drawer.component.scss
lib/src/modal/modal.service.ts
lib/src/navbar/navbar-menu/navbar-menu.component.scss
lib/src/navbar/navbar.component.scss
lib/src/popover/popoverContent.component.scss
lib/src/sass/_variables.scss
lib/src/select/select.component.scss
lib/src/subnav/subnav.component.scss
tsconfig.json

When integrating the current Cashmere as an NPM package into Fabric.Auth.AccessControl, I found that the popover likes to pop under:
This solved the issue.

Set `z-index` of popover so it pops... over.

---

lib/src/button/button.component.scss

Thanks for catching this @isaaclyman.  Disabled buttons currently were switching to a gray color that was lost when placed directly against our gray page background.  As @corykon pointed out, the switch to gray also loses any context from the color of the button (ie red for destructive).  To address both these issues, switching to a 35% drop in opacity when a button is disabled instead.

Disabled buttons drop to 35% opacity

---

docs/polyfills.ts

IE 11 doesn't have object.assign, a quick google led to this very simple solution. Tested the popover now triggers properly 😄 
Closes #199

add core-js/es6/object poly fill to fix IE11 popover bug

---

lib/src/sass/tables.scss

In a module I was working on I wanted a way to disable hover states on the .hc-table. This will allow that to happen by doing the following
```
<tr disabled><tr>
// or in angular 
<tr [attr.disabled]="disabled ? '' : null"></tr>
```

no hover on disabled row

---

docs/app/components/typeform-survey/typeform-survey-demo.component.html
docs/app/guides/guides.service.ts
guides/contribution-guide.md
guides/submit-an-issue.md
guides/user-feedback.md

This is content I requested from the Operations team back when @corytak built the [Typeform component](https://cashmere.healthcatalyst.net/components/typeform-survey).  So they wrote this, I've just converted it into markdown.  Catalyst is asking our apps to prompt the user for feedback on regular intervals, and this guide is a place to explain why and how we're doing that.  It also allows us to pull body copy recommendations out of the component documentation and into the guide.
Also fixed an issue where the `:::` was indented in two of the current guides and the interpreter was reading that as creating another `hc-tile` inside the current tile.

User feedback guide

---

projects/cashmere/package.json

Peer dependencies now use a range to prevent user from needing specific dependency versions
Closes #272

Cashmere peerdependencies

---

projects/cashmere/src/lib/button/split-button/split-button.component.html
projects/cashmere/src/lib/button/split-button/split-button.component.spec.ts
projects/cashmere/src/lib/button/split-button/split-button.component.ts

split-button captures menu clicks and calls stopPropagation to prevent primary button from being
triggered
fix #345

fix(split button): fixes split-button onClick issue

---

projects/cashmere/src/lib/subnav/subnav-right.directive.ts
projects/cashmere/src/lib/subnav/subnav.component.ts
projects/cashmere/src/lib/tile/tile.component.ts

documents subnav and tile components' public api while hiding fields/methods that are private
closes #310 & #312

docs: add jsdocs for subnav & tile components

---

projects/cashmere/src/lib/sass/_tabs.scss
src/app/components/component-list/components-list-router.module.ts
src/app/components/component-viewer/component-api/component-api.component.scss
src/app/components/component-viewer/component-api/component-api.component.ts
src/app/components/component-viewer/component-api/document-viewer/document-viewer.component.scss
src/app/components/component-viewer/component-examples/component-examples.component.scss
src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.html
src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.ts
src/app/components/component-viewer/component-viewer.component.html
src/app/components/component-viewer/component-viewer.component.scss
src/app/components/component-viewer/component-viewer.component.ts
tools/dgeni/templates/class.template.html
tools/dgeni/templates/componentGroup.template.html
tools/dgeni/templates/method-list.template.html

Updates to the style of the dgeni templates following [the prototype](https://xd.adobe.com/view/7a081799-3095-46c2-b22b-3b9f6393eb1d/screen/9f562696-4bae-4b0f-9b89-fd07a33fe5b4/Components-API) that was vetted with the community.
Styling the dgeni docs was actually really nice, they give unique classes to just about everything, so I was happy how smoothly that went.  @corykon - I'd love to have your eye on my changes and see if there's anything you'd do differently from a design perspective.  
A few next steps for us to look at if you guys are good with this update:
1. **Style Resets** - There is something weird since we did this dgeni update going on with the css when you go between "Styles" or "Guides" and "Components".  It's almost like the css gets reset or overridden now when you go …

docs: doc styling

---

projects/cashmere/src/lib/input/hc-form-field.component.scss

sets a minimum width for input element and removes the explicit width
fix #363

fix(hc-form-field): fixes input element overflow

---

guides/getting-started.md

Updated getting-started with angular-cli@6 instructions. Gave instructions that follow best
practices for importing third-party libraries by using a module dedicated for that library
closes #381

docs(getting-started.md): updated getting-started.md

---

projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.html

Including the app switcher in the example made it fail because the app switcher needs to be provided. I was thinking of getting a non app switcher navbar out for now and eventually getting another example with it later

fix(navbar): removed app switcher from component example

---

scripts/guide-copy-assets.js

copying of assets checks to see if TRAVIS environment variable is set to determine where assets need
to be copyied

ci(guide-copy-assets.js): fix copying of assets for gh pages

---

.releaserc.json

updated semantic-release github release to publish correct tgz file

ci(.releaserc.json): correctly publish compiled tgz to github

---

.prettierignore
projects/cashmere/src/lib/select/select.component.scss

fix(select.component): select inherits font instead of using system font

---

src/app/components/component-viewer/shared/document-viewer/document-viewer.component.scss

corrects `<th>` elements from being centered in webkit browsers
closes #429

docs(css): webkit th text alignment

---

projects/cashmere/src/lib/sass/_tabs.scss
projects/cashmere/src/lib/tabs/tab-set.component.html

Removes text wrap from tab titles and truncates if the title is too long for the space (thanks for the `hc-text-ellipsis` class, @corykon) .  I agree with @jtrujill that for layout purposes, the tabs shouldn't go multi-line.  Obviously for the best UX, tabs shouldn't normally be truncated, but this gives a way for them to compress elegantly when screen real estate is limited.  See example:
closes #257

fix(tabs): remove multiline

---

guides/naming-conventions.md
src/app/guides/guides.service.ts

I'm just the scribe on this one.  Turned the conversation from the thread into a markdown file for our naming conventions guide.  Let me know if any of the content is unclear or needs to change.
@jtrujill - I know you said you are opposed to the "Component" or "Directive" in the component names.  I still included it in this guide because that's how everything is currently named in the library, so I don't want to create confusion.  Seems like that change should be submitted as an issue to wholesale remove those labels from the components in the library.  And then if we do that we can change the guide to match.
closes #411

docs(naming): adds naming convention guide

---

projects/cashmere/src/lib/modal/modal-options.ts
projects/cashmere/src/lib/modal/modal.service.ts

sets ActiveModal.data earlier so that when a modal component instance is created it's available in
the constructor. Replaced deprecated ReflectiveInjector with Injector.create. ModalOptions is now
an interface since it wasn't being used as a class anywhere.
fixes #476

fix(modal): access to ActiveModal.data now allowed in constructor

---

projects/cashmere/src/lib/accordion/accordion.component.ts

Simple change so that when we check the isOpened and isClosed getters in an emitted opened or closed event, they return true.

Set accordion currentlyAnimating prior to emitting

---

projects/cashmere-examples/src/lib/input-required/input-required-example.html
projects/cashmere-examples/src/lib/input-required/input-required-example.ts
projects/cashmere/src/lib/input/hc-form-field.component.html
projects/cashmere/src/lib/input/hc-form-field.component.scss

Highlight in $error red an input field that is invalid.  Also adds the ability to demonstrate this functionality in the required input example.
closes #497

fix(input): highlight on invalid

---

guides/using-and-customizing-components.md

recommend the use of Cashmere CSS class naming conventions for SCSS mixins instead of BEM

docs(guides): replace BEM with project convention

---

projects/cashmere-examples/src/lib/radio-button-forms/radio-button-forms-example.css
projects/cashmere-examples/src/lib/radio-button-forms/radio-button-forms-example.html
projects/cashmere-examples/src/lib/radio-button-forms/radio-button-forms-example.ts
projects/cashmere/src/lib/radio-button/radio-button.component.scss
projects/cashmere/src/lib/radio-button/radio.ts
projects/cashmere/src/lib/sass/_radio-group.scss
projects/cashmere/src/lib/sass/cashmere.scss

Fixes the the margin/padding css on radio buttons so that the button circle is centered around the text - rather than the other way around.  The top and bottom of the circle should now extend equal amounts above and below the text.  Also added support for horizontal as well as vertical button groups via a boolean `vertical` input added to the radio group selector.  Updated the last example on the radio button page to illustrate a horizontal button group.
closes #452

fix(radio button): radio group orientation

---

projects/cashmere/src/lib/chip/chip.component.scss

Good catch @jtrujill.  It's useful to have the margin for the sake of the chip-rows, but they absolutely should be centered.
closes #535

style(chip): center margins

---

projects/cashmere/src/lib/select/select.component.scss

@corykon - ended up writing a little bit of Firefox specific CSS to get around that focus highlight issue where the dotted line wasn't covering the whole box.  Basically that's just the way Firefox handles their bounding box - it doesn't include padding.  So I'm hiding Firefox's highlight, and adding a dotted line styled the same way within :focus to still follow the overall browser style - but cover the whole box.
I also added `line-height: normal;` to correct the issue where the bottom of text was still getting cropped on Mac Chrome.
closes #506, #478

style(select): firefox focus

---

projects/cashmere-examples/src/lib/select-forms/select-forms-example.css
projects/cashmere-examples/src/lib/select-forms/select-forms-example.html
projects/cashmere/src/lib/input/hc-form-field.component.scss
projects/cashmere/src/lib/label/label.component.scss
projects/cashmere/src/lib/label/label.component.ts
projects/cashmere/src/lib/sass/_typography.scss
projects/cashmere/src/lib/select/select.component.scss

Mostly a temporary fix until hc-label is deprecated and hc-select can use hc-form-field.  But this ensures that they don't have css styles colliding, and it brings the colors, font sizes, etc in line with each other.
closes #507

style(label): remove style collision

---

projects/cashmere/src/lib/button/button.component.scss
projects/cashmere/src/lib/sass/button.scss

Cashmere colors and functions were being imported to the component scss file instead of the mixins
file where they were used. This was a bug and it was my bad. It is now fixed.

fix(button): import cashmere colors/fns to the mixins file

---

projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.css
projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.html
projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.ts
projects/cashmere/src/lib/tabs/index.ts
projects/cashmere/src/lib/tabs/tab-set.component.html
projects/cashmere/src/lib/tabs/tab-set.component.ts
projects/cashmere/src/lib/tabs/tab.component.ts

- Adds a `selectChange` emitter to `TabSetComponent` that fires when the select tab in the set is changed.  
- Add a `selectTab` function to `hc-tab-set` that allows the selected tab to be set programmatically via either a numerical index or a `TabComponent` object
- Adds a `tabClick` emitter on `TabComponent` that fires when the tab is clicked.  `(click)` doesn't work because the tabs are generated in the tab-set template separately from the content.  So the click is being attached to something that doesn't exist.  But this emitter gets around that and will allow apps to bind events to tab clicks.
- Updated the Horizontal Tab example to illustrate all of the above.
closes #255, closes #556, closes #548

Tab Event Handling

---

projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.css
projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.html
projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.ts
projects/cashmere-examples/src/lib/radio-button-forms/radio-button-forms-example.css
projects/cashmere-examples/src/lib/radio-button-forms/radio-button-forms-example.html
projects/cashmere-examples/src/lib/radio-button-forms/radio-button-forms-example.ts
projects/cashmere/src/lib/checkbox/checkbox.md
projects/cashmere/src/lib/radio-button/radio-button.component.scss
projects/cashmere/src/lib/radio-button/radio-button.md
projects/cashmere/src/lib/radio-button/radio.ts
projects/cashmere/src/lib/sass/_radio-group.scss
projects/cashmere/src/lib/sass/form-field.scss
src/app/core/document-items.service.ts

Adds support for `hc-form-field` to `hc-radio-group`.  Note the name change on the parameter `vertical` in RadioGroupDirective to `inline`.  That just came out in the last release, so I think it's still new enough to change safely, but I've asked on the Slack channel to see if I'm wrong.  `inline` is a better descriptor and matches the naming convention used in `hc-form-field`.
closes #566

feat(radiobutton): form field support

---

projects/cashmere/src/lib/sass/checkbox.scss

Space created by margin is considered outside the element, so it doesn't get a click event.  Switching to padding resolves that.
closes #604

style(checkbox): fixes hit area

---

projects/cashmere/src/lib/pagination/pagination.component.html
projects/cashmere/src/lib/pagination/pagination.component.ts
projects/cashmere/src/lib/select/select.component.html
projects/cashmere/src/lib/select/select.component.ts

if the total items being paged is smaller than the page size, display "Showing all of n" instead of
i.e. "Showing 20 of 5"
fix #639

fix(pagination): display `all` when length < page size

---

projects/cashmere/src/lib/sass/navbar.scss

insure we don't inherit line height from somewhere else and throw off vertical alignment
re #644

fix(navbar): explicitly set line height

---

projects/cashmere/src/lib/banner/hc-banner.scss

There are some flex box issues with IE that can be solved with setting the justify-content to
flex-start
(Ignore the small chunk of scroll bar that's covering some of the banner, there are tons of other IE issues at the moment...)
Thanks @YaroBear for finding this solution and helping me out!
Fixes issue #684

fix(hc-banner): flex start justify content

---

guides/using-and-customizing-components.md
projects/cashmere/src/lib/accordion/accordion.component.scss
src/app/components/components.component.html
src/app/components/components.component.scss
src/app/components/components.component.ts
src/app/core/document-items.service.ts
src/app/guides/guides.component.html
src/app/guides/guides.component.ts
src/app/guides/guides.service.ts
src/app/styles/styles-routes.module.ts
src/app/styles/styles.component.html
src/app/styles/styles.component.ts
src/styles.scss

Some much needed improvements to the navigation of the demo site.  You'll see that I kept the `hc-tabs` because I didn't want to reinvent the wheel on all its routing functionality, but I hid the left portion and replaced it with my new fixed navigation tile (leveraging our `hc-accordion` component)
For anyone on a Windows computer, can you send me a screenshot of what the scrollbar on the left nav tile looks like when you expand several sections?  Not totally sure whether the tile will expand horizontally to accommodate it or if it will stick out off the edge.
closes #655

feat(all): demo site navigation

---

projects/cashmere/src/lib/app-switcher/app-switcher.service.spec.ts
projects/cashmere/src/lib/app-switcher/app-switcher.service.ts
projects/cashmere/src/lib/navbar/navbar.md

add validation and normalization for the app switcher configuration; also provide documentation on
how to provide discoveryServiceUri to the app swithcer at runtime (as opposed to AOT build time)
fix related to this conversation:
Joe Skeen [4 hours ago]
Is anyone using the Cashmere App Switcher in a DOS app?  I've tried a few ways to hook up the discovery service and only getting part of it to work.  In IDEA, the `discoveryServiceUri` is being hard-coded to `'/DiscoveryService`, but it should be getting that value instead from the web.config.  In Atlas I'm able to pass in `window.discoveryServiceRoot`, which makes getting the apps work, but not the "All Apps" page (it goes to `/DiscoveryService/v1/apps` which is a 404
Ty Jones [4 hours ago]
We were seeing some bugs around that where the …

fix(app-switcher): make app switcher configuration more flexible

---

projects/cashmere/src/lib/sass/_subnav.scss
src/app/components/components.component.scss

Corrects positioning of nav elements in IE11 on the demo site.  A few interesting learnings to note here:
- IE doesn't handle `position: fixed` the same as Chrome.  You need to set a `left` value or the element will just be floating out wherever.
- IE doesn't handle the flex parameter `align-items: center;` for vertical alignment unless a height is set for the element.  If only `min-height` is set, it won't work.
closes #707

fix(all): IE11 nav css fix

---

projects/cashmere/src/lib/sass/button.scss

IE11 fix to fix min-width constraint on split buttons
closes #698

fix(button): IE11 split button width

---

projects/cashmere/src/lib/sass/about-modal.scss

adds an explicit svg img width for IE11
closes #699

fix(about): center header

---

projects/cashmere/src/lib/sass/input.scss

corrects vertical alignment for input text boxes in IE11
closes #692

fix(input): IE11 vertical alignment

---

projects/cashmere/src/lib/sass/tables.scss

corrects table border padding for thicker border tables which was causing IE11 to display overflow scroll bars where it shouldn't be.
closes #696

fix(table): border width fix

---

projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
projects/cashmere/src/lib/sass/navbar.scss

Removes flex style on navbar logo to prevent IE11 from collapsing on it.  Also noticed that at the mobile breakpoint on IE, the second mobile menu was visible.  But on all browsers, when the second example's mobile menu was opened, it couldn't be closed (because it was behind the main site nav).  So I hid the navbar in the example, but included a comment so devs would know that shouldn't go in their code if they're copy/pasting.
closes #705

fix(navbar): IE11 logo display style

---

projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.scss

changes `flex-basis` to auto (the default value) for each column for compatibility
closes #704

fix(datepicker): IE11 flex layout

---

projects/cashmere/src/lib/sass/tables.scss
src/styles.scss

Reduces bordered tables to 1px width; fixes dashed rows on demo site.  The 2px thickness on the bordered version of tables has always felt too heavy to me.
closes #700

style(table): border styles

---

projects/cashmere/src/lib/app-switcher/app-switcher.module.ts

add AppSwitcherComponent to NgModule.EntryComponents
Due to the issues with Popper.js in Atlas, I have tried to switch to an Angular CDK version for the App Switcher; unfortunately, the `AppSwitcherComponent` is not in `entryComponents` so it can't be used to create a `ComponentPortal`.  This should fix that.

fix(app-switcher): add to entryComponents

---

projects/cashmere/src/lib/radio-button/radio.ts

Properly sets checked and value parameters on radio groups.  Yikes, that was a pretty serious bug.  Thanks for spotting that @Br00t4L17y.  Looks like the value wasn't even getting set correctly for a group on change.  And the radio's change function was trying to set the checked state independent of the group - which was screwing up the logic in the group because it thought the button was already checked.
closes #752

fix(radio-button): group change fix

---

projects/cashmere-examples/src/lib/tabs-vertical/tabs-vertical-example.component.html
projects/cashmere/src/lib/tabs/tab-set.component.ts

Adds a defaultTab property to hc-tab-set which includes the ability to set to "none" - which prevents any tab from being selected initially.  How does this work to address the issue you ran into @jonest?
closes #754

feat(tabs): defaultTab property

---

projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.spec.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts

When  I removed the start/end dates and used the year/month calendar views to set the start date to
a day in the future (which I was able to) and set the end date to "today's date". The "Apply" button
is enabled. In this scenario, I was expecting the "Apply" button to be
fix #763

fix(date-range): when dates are null minmax values are not enforced

---

projects/cashmere/src/lib/drawer/drawer.component.ts

Stops the toggle function from interrupting animation and throwing an error.  I'm pretty sure this was a mistake in the toggle function because it was setting `_drawerOpened` twice both inside and outside of the `animationPromise` logic.  As best as I can tell the component wasn't written to have its animation interrupted - hence the error.
closes #766

fix(drawer): prevent animation interupt

---

projects/cashmere/src/lib/radio-button/radio-button.component.spec.ts
projects/cashmere/src/lib/radio-button/radio-group.directive.spec.ts
projects/cashmere/src/lib/radio-button/radio.ts

Adds unit tests for radio buttons and radio groups.  I'm pretty new to writing unit tests, so I'd appreciate any feedback you have.  The radio buttons are pretty similar in form to the checkbox which had unit tests already, so I tried to model after them.
closes #621

test(radios): radio button unit tests

---

projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
projects/cashmere/src/lib/app-switcher/app-switcher.component.html
projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
projects/cashmere/src/lib/app-switcher/app-switcher.component.ts
projects/cashmere/src/lib/navbar/navbar.md

Corrects app icons that were being stretched if they weren't square.  Adds an app switcher parameter to set the height to something other than 100px if needed.  Also fixes an issue where the names weren't being centered correctly under the icons.

fix(appswitcher): thumbnail img sizing

---

projects/cashmere-examples/src/lib/typeform-survey-overview/typeform-survey-overview-example.component.html
projects/cashmere/src/lib/typeform-survey/typeform-survey.component.ts

Adds a field to specify an app version number for the survey and appends it as a hidden field.  The Slack reporting and EDW import of the survey results will be updated to look for the `app_version` value and include it in any reporting.
closes #768

feat(typeform_survey): app version

---

src/app/components/component-viewer/component-viewer.component.html
src/styles.scss

Overrides the default horizontal tab overflow to not clip box-shadow on our demo site content viewer.  I thought of doing this as an additional parameter to tabs - but no one has asked for it, so I'm assuming most devs would do an override like this anyway.
closes #590

fix(component-viewer): overflow visible

---

projects/cashmere-examples/src/lib/resizable-columns/resizable-columns-example.component.html
projects/cashmere-examples/src/lib/table-sort/table-sort-example.component.html
projects/cashmere/src/lib/sass/tables.scss
projects/cashmere/src/lib/table/cell.ts
projects/cashmere/src/lib/table/table.md
src/app/styles/table/table-demo.component.html

Adds text justify options to component and table styles.  This is a pretty important feature, I'm amazed it didn't come up sooner.  I've built it so the dev has some options when it comes to alignment - they can choose to right justify, but keep the sorting indicator to the right as well if that's preferred (I was asked about this recently).
closes #646

feat(tables): cell text justify

---

projects/cashmere/src/lib/icon-font/hcicons.css
src/app/styles/icons/icon-guide.component.html

corrects a css collision on `hc-link`
closes #833

fix(icons): resolve naming collision

---

projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-custom.component.ts
projects/cashmere/src/lib/toaster/hc-toaster.service.ts

`close()` function now correctly updates service when called on any HcToastRef.  Great catch on this one @isaaclyman - in looking back at the service, the way I was handling close cleanup was pretty goofy.  It's all tied to the completion of the animation event now (which HcToastRef close() triggers).  So everything is cleaner and more logical.
Made a minor fix to the custom component example as well while I was in there to handle full width versions.
closes #842

fix(toasts): HcToastRef close()

---

projects/cashmere/src/lib/toaster/hc-toast.component.ts
projects/cashmere/src/lib/toaster/hc-toaster.service.ts

Detects changes on addToast to fix changed after checked error.  @isaaclyman - I tested this out by modifying the toast example to show a toast via `ngOnInit`.  I was getting the same error you referenced, but this change appears to fix the problem.  Let me know if this works in your case as well.  Thanks!
closes #844

fix(toasts): change detection

---

README.md

I fixed the contribution guide, but missed the `Readme.md` instructions on running the demo application.  This way by default you will get the whole library to live reload.

docs(readme): update demo app instructions

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/doc_request.md
.github/ISSUE_TEMPLATE/feature_request.md

My goals here are to:
1. Significantly reduce friction for Cashmere outsiders who want to report issues
2. Make documentation a first-class citizen by inviting Cashmere users to recommend improvements to it
Potential objections: I understand the impulse to ask for as much information as possible from issue creators, but in my experience this makes people feel like submitting an issue isn't worth the trouble. Most software bugs and feature requests can be effectively described in a sentence or two. If a bug report is severely lacking in detail or we're unable to reproduce it, we should take a moment to follow up and ask for specific clarification.
In short, if we want participation from the Health Catalyst community, we should make it easy for them to participate.

docs(issue template): simplify existing templates and add doc template

---

projects/cashmere-examples/src/project-template/src/styles.scss

Seems to fix #892 
Someone should validate though! Run a fresh `npm run build`, fire up the app, then open the stackblitz example for hc-icons component.

docs(hc-icons): fix hc-icons in stackblitz examples

---

projects/cashmere/src/lib/breadcrumbs/breadcrumbs.component.ts

since Angular doesn't export it consistently each version, we include it
in Cashmere
Closes #924

fix(breadcrumbs): fix import

---

projects/cashmere/src/lib/scroll-nav/content/scroll-nav-content.component.ts

docs(scrollnav): makeLastTargetFullHeight defaults to true, not false

---

projects/cashmere-examples/src/lib/chip-singlerow/chip-singlerow-example.component.html
projects/cashmere-examples/src/lib/chip-singlerow/chip-singlerow-example.component.scss
projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.html
projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.scss

Alejo and I had the opportunity to attend a UX Research training this past week, and as part of it we conducted a user test around the functionality of the filters drawer.  We discovered (see results below), that users really struggled to know how to trigger the drawer.  But once they opened the drawer, they were able to filter fine.  So I've discussed with the UX team and we are proposing a style change to make the trigger more prominent and more button-like.
Once these changes are merged, I'll work on broadcasting this out to all the product teams to make the change.

docs(filters): updated filter styles

---

projects/cashmere/src/lib/icon-font/hcicons.scss

Removes color properties on two icons in the catalyst set.  Was preventing the color from being set on these icons.
closes #980

style(icons): remove color styles

---

projects/cashmere/src/lib/pop/popover-anchoring.service.ts
projects/cashmere/src/lib/sass/_cdk-overlay.scss
projects/cashmere/src/lib/sass/_toaster.scss
projects/cashmere/src/lib/sass/cashmere.scss
projects/cashmere/src/lib/toaster/hc-toaster.service.ts

Removes pointer events on popover to prevent hover flickering
Looks like I had already needed to address this on the overlay for toasts, so I just made the toast fix class general and applied it to the popover overlay.
closes #861

fix(popover): fixes center hover flickering

---

projects/cashmere-examples/src/lib/input-text-area/input-text-area-example.component.html
projects/cashmere-examples/src/lib/input-text-area/input-text-area-example.component.ts
projects/cashmere/src/lib/form-field/hc-form-field.component.scss
projects/cashmere/src/lib/sass/form-field.scss
src/app/core/document-items.service.ts

adds textarea example and corrects input suffix padding
closes #965
closes #983

fix(input): textarea example

---

projects/cashmere/src/lib/modal/modal-window.component.ts

prevents a click drag outside a modal from accidentally closing it
closes #998

fix(modal): click drag outside modal

---

projects/cashmere/src/lib/sass/checkbox.scss
projects/cashmere/src/lib/sass/radio-button.scss

Adjusts the spacing between radio buttons to match checkboxes.
Great eye on this one @joeskeen - I completely missed this.  I measured the adjust version in Photoshop to double check, and everything is 100% identical now.
closes #955

fix(radio): match margins to checkbox

---

projects/cashmere-examples/src/lib/pagination-simple/pagination-simple-example.component.ts
projects/cashmere/src/lib/pagination/base-pagination.ts

Stops initial value of pageSize from being overwritten to the default.  I starred at this one for hours thinking it had something to do with base class inheritance.  Turns out it just had to do with the two-way binding being broken;  the pageSize setter wasn't emitting on a change.
closes #776

fix(pagination): initial value of pageSize

---

projects/cashmere/src/lib/tabs/tab-set/tab-set.component.spec.ts
projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
projects/cashmere/src/lib/tabs/tab/tab.component.html
projects/cashmere/src/lib/tabs/tab/tab.component.spec.ts
projects/cashmere/src/lib/tabs/tab/tab.component.ts
projects/cashmere/src/lib/tabs/tabs.service.ts

Remove dependency on TabsService. TabSetComponent and TabComponent no longer need it. Instead TabComponents are not rendered until their direction is set by their TabSetComponent.
@joeskeen : I had to add the use of setTimeout when setting the direction. I looked in the console and found that Angular was throwing because its value changed before the change detection cycle completed.

feat(tab): remove tabs service

---

projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.scss
projects/cashmere/src/lib/toaster/hc-toaster.service.ts

Ensures cleanup functions are called on close with multiple toasts.  The `takeUntil` pipe was preventing the cleanup functions from being called more than once when multiple toasts were open.  
@joeskeen can you verify there aren't any unintended consequences from removing that pipe?  I'm not entirely sure why it was there in the first place, it may have been an artifact of an earlier version.
closes #1018

fix(toasts): closing multiple toasts

---

projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.scss
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
projects/cashmere/src/lib/datepicker/calendar-body/calendar-body.component.html
projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts
projects/cashmere/src/lib/datepicker/datepicker.component.spec.ts
projects/cashmere/src/lib/datepicker/datepicker.md

fix that prevented validation when the initial bound value wasn't set
closes #982

fix(datepicker): validation with null init value

---

projects/cashmere-examples/src/lib/popover-overview/popover-overview-example.component.html
projects/cashmere-examples/src/lib/popover-right-click/popover-right-click-example.component.html
projects/cashmere-examples/src/lib/popover-right-click/popover-right-click-example.component.ts
projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
projects/cashmere/src/lib/pop/popover-anchoring.service.ts
projects/cashmere/src/lib/pop/popover.component.ts
projects/cashmere/src/lib/pop/types.ts
src/app/core/document-items.service.ts

Adds a right-click trigger to HcPop, the ability to position the popover based on the triggering click, and a popover context parameter that let's the developer store info about the popover (@corykon pointed out similar functionality in [this component](https://www.npmjs.com/package/ngx-contextmenu)).  Also added a new example to demonstrate the right-click context menu functionality, and updated the existing overview example with the new options.
While I was in there, I also submitted a fix for the `autoCloseOnContentClick` bug recently reported.  I saw it coming up in my example.  The reason for the bug was the `_overlayRef` in the service was coming back as `undefined` when close() was called from the component.  My fix is to store a reference to the component's overlay in a reference …

Right-click Trigger on HcPop

---

projects/cashmere/src/lib/sass/checkbox.scss

updated styling for indeterminate checkboxes
closes #1039

style(checkbox): indeterminate styles

---

projects/cashmere/src/lib/button/button.component.ts
projects/cashmere/src/lib/pagination/load-more-pagination.component.spec.ts

I got an console error that said "Unsupported style input value: undefined". It took me a while to figure out what it was talking about, so I wanted to clarify the validation errors thrown by ButtonComponent.

docs(button): improve button validation errors

---

guides/styles/about-modal.md
projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.html
projects/cashmere-examples/src/lib/popover-menu/popover-menu-example.component.html
projects/cashmere/src/lib/navbar/navbar.md
projects/cashmere/src/lib/sass/_menu.scss
projects/cashmere/src/lib/sass/about-modal.scss
src/app/styles/about/about-modal.component.html

Allow hcMenuItem to support anchors as well as buttons. Also two small adjustments to the about-modal stylesheet (based on my implementation of it in AccessControl).
closes #1069

fix(popover): hcMenuItem support anchors

---

projects/cashmere/src/lib/navbar/navbar.component.html
projects/cashmere/src/lib/navbar/navbar.component.spec.ts
projects/cashmere/src/lib/navbar/navbar.component.ts
projects/cashmere/src/lib/sass/navbar.scss

Improves collapsing links into more menu; prevents link text wrapping.  Still doesn't eliminate the `setTimeout` on `ngAfterViewInit` - but @corykon and I were struggling to come up with a way to clever remove that hack.
closes #1066
closes #671

fix(navbar): improved more menu

---

projects/cashmere/src/lib/toaster/hc-toaster.module.ts

HcToast is dependant on the Overlay module, so module now imports it.
@joeskeen @corykon - I'm pretty sure this is all we need to do to fix the issue we saw in AccessControl on this.  I tried removing the OverlayModule import there, and swapped it with a PopModule import from Cashmere, which also resolved the issue.  PopModule imports OverlayModule, but only exports BidiModule.  I tried importing BidiModule independently on AccessControl (to see if that was fixing the issue), but the error returned.  So I'm pretty sure that if we just import OverlayModule in the Toaster module - that's all we need to do.
Let me know what you think.
closes #1091

fix(toaster): import Overlay module

---

projects/cashmere-examples/src/lib/popover-menu/popover-menu-example.component.html
projects/cashmere/src/lib/pop/directives/menu-item.directive.ts
projects/cashmere/src/lib/pop/directives/menu.directive.ts
projects/cashmere/src/lib/pop/popover.component.html
projects/cashmere/src/lib/pop/popover.component.ts
projects/cashmere/src/lib/sass/_menu.scss

Allows users to navigate hcMenus using arrows or tab keys.  
Give this one a look over @corykon.  I noticed when I was looking at Google docs that it's important keyboard navigation and mouse highlighting need to stay synced up.  So that's why I used focus as a way for all of them to work together.
closes #1049

feat(hc-menu): keyboard navigation

---

projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.html
projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.ts
projects/cashmere/src/lib/navbar/navbar.component.scss
projects/cashmere/src/lib/sass/navbar.scss

Allow the navbar username block to support two lines of text. Also removes the 150px `max-width` cap on the username.  Updated one of the navbar examples to demonstrate a username block with two lines.  Let me know what you all think.
closes #1105

fix(navbar): support two line username

---

projects/cashmere/src/lib/app-switcher/app-switcher.component.html
projects/cashmere/src/lib/app-switcher/app-switcher.component.scss
projects/cashmere/src/lib/navbar/navbar.component.ts

navbar supports links added after load & non-square app switcher icons
@corykon this should knock out two of the three issues you reported.  Can we put the table styles one into a separate issue?
closes #1110

fix(navbar): dynamic links & switcher styles

---

projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts
projects/cashmere/src/lib/date-range/date-range/date-range.directive.spec.ts
projects/cashmere/src/lib/date-range/date-range/date-range.directive.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.spec.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts

Allow multiple presets with same date ranges & selectedDate may be number.  @jacquie the DatePicker definitely wasn't set up to support your use case, so it required some well needed house cleaning.  The good news is that it's leaner and meaner than before - and I believe it now should do what you need it to.  I've updated our example a prove out the functionality (it has two presets with the same value).
Please give it a good look over and ensure that the functionality looks like it's got you covered.
closes #1111

fix(datepicker): support preset overlapping values

---

projects/cashmere/src/lib/sass/table.class.scss
projects/cashmere/src/lib/sass/table.scss

fix #1114
So sort icons are position correctly when applying `.hc-table-small`

fix(table styles): fix small table header styles

---

projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts

Fixes two digit year conversion in IE to match other browsers.  This correction applies to both the datepicker and daterange components.
closes #1042

fix(datepicker): two digit year conversion

---

projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts
projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts

Disables today button only if current month is outside min or max.
I'm glad you brought this one up @Techgeekster because it had been bugging me too.  The calculation for disabling the Today button came from when clicking Today selected the current date.  Now it just jumps to the current date, but the user still needs to make a selection.  So the today button should only be disabled if the entire month that today falls under is outside of the range of the min or max.
closes #1125

fix(datepicker): today button disabled

---

projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts
projects/cashmere/src/lib/datepicker/datepicker.component.ts

Correctly display init values when the mode is something other than date.  Thanks for finding this one @Techgeekster!
closes #1141

fix(datepicker): init values with reactive forms

---

projects/cashmere-examples/src/lib/pagination-load-more/pagination-load-more-example.component.ts
projects/cashmere-examples/src/lib/pagination-standard/pagination-standard-example.component.ts
projects/cashmere/src/lib/pagination/pagination.component.html
projects/cashmere/src/lib/pagination/pagination.component.scss
projects/cashmere/src/lib/sass/pagination.scss

Fixed the following:
- fix #1135, pageSize change event was broken because of the new `SelectChangeEvent` fired by hc-select
- prevent wrapping on the "of 'x' entries label
- prevent `ExpressionChangedAfterItHasBeenCheckedError` on pagination examples

1135 Pagination bugs

---

projects/cashmere/src/lib/sass/app-switcher.scss

corrects the max-width for the smaller default icon sizes
closes #1155

style(appswitcher): max width

---

projects/cashmere/src/lib/sass/navbar.scss

the username section of the navbar could bleed outside of its container in IE
fix #1157

fix(navbar): fix IE styles

---

projects/cashmere/src/lib/picklist/pane/picklist-pane.component.html
projects/cashmere/src/lib/sass/table.class.scss

removes the no-hover class from the picklist (really not needed for this component), and makes the no-hover class more compatible with selected rows in case they were being used together elsewhere.
fix #1172

fix(picklist): fix selected row hover bug

---

projects/cashmere/src/lib/tabs/tab/tab.component.html
projects/cashmere/src/lib/tabs/tab/tab.component.ts

stops the router being called on the host as well as the anchor on a tab
closes #1179

fix(tabs): prevent router being called twice

---

projects/cashmere-examples/src/lib/banner-overview/banner-overview-example.component.html
projects/cashmere-examples/src/lib/checkbox-forms/checkbox-forms-example.component.ts
projects/cashmere-examples/src/lib/checkbox-indeterminate/checkbox-indeterminate-example.component.html
projects/cashmere-examples/src/lib/checkbox-standard/checkbox-standard-example.component.html
projects/cashmere-examples/src/lib/date-range-time/date-range-time-example.component.html
projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts
projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.component.html
projects/cashmere-examples/src/lib/form-field-tight/form-field-tight-example.component.html
projects/cashmere-examples/src/lib/input-suffix/input-suffix-example.component.html
projects/cashmere-examples/src/lib/popover-overview/popover-overview-example.component.html
projects/cashmere-examples/src/lib/progress-spinner/progress-spinner-example.component.html
projects/cashmere-examples/src/lib/select-standard/select-standard-example.component.html
projects/cashmere-examples/src/lib/select-validation/select-validation-example.component.html
projects/cashmere-examples/src/lib/stepper-overview/stepper-overview-example.component.html
projects/cashmere-examples/src/lib/tabs-vertical/tabs-vertical-example.component.html
projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.html
projects/cashmere/src/lib/button/button.md
projects/cashmere/src/lib/checkbox/checkbox.md
projects/cashmere/src/lib/date-range/model/model.ts
projects/cashmere/src/lib/date-range/services/config-store.service.ts
projects/cashmere/src/lib/form-field/form-field.md
projects/cashmere/src/lib/input/input.md
projects/cashmere/src/lib/radio-button/radio-button.md
projects/cashmere/src/lib/select/select.md
src/app/core/document-items.service.ts

Updates standards for text formatting on all form fields (following the model established for Select).  Also updates the examples on the Cashmere site to follow the new standards.
closes #1178

docs(form-fields): form field formatting

---

projects/cashmere-examples/src/lib/select-forms/select-forms-example.component.html
projects/cashmere-examples/src/lib/select-forms/select-forms-example.component.scss
projects/cashmere-examples/src/lib/select-forms/select-forms-example.component.ts
projects/cashmere/src/lib/select/hc-option.directive.ts
projects/cashmere/src/lib/select/select.component.ts
projects/cashmere/src/lib/select/select.module.ts

WOOHOO! `hc-select` now supports form ngValues as objects as well as strings.  It emits objects and you can set a formControl or ngValue with an object.  No additional markup required.  The last example on the Select page has been updated to demonstrate the functionality.
What a mind-bender this one was, but thanks @joeskeen for the suggestion to try `option[ngValue]` as the selector for the directive.
closes #779

fix(select): objects in ngValue

---

guides/styles/login-page.md
projects/cashmere-examples/src/lib/datepicker-selected-value/datepicker-selected-value-example.component.html
projects/cashmere-examples/src/lib/ellipsis-overview/ellipsis-overview-example.component.html
projects/cashmere-examples/src/lib/input-required/input-required-example.component.html
projects/cashmere-examples/src/lib/pagination-simple/pagination-simple-example.component.html
projects/cashmere-examples/src/lib/table-filter/table-filter-example.component.html
projects/cashmere/src/lib/checkbox/checkbox.md
projects/cashmere/src/lib/date-range/services/config-store.service.ts
projects/cashmere/src/lib/form-field/form-field.md
projects/cashmere/src/lib/input/input.md
projects/cashmere/src/lib/radio-button/radio-button.md
projects/cashmere/src/lib/select/select.md
src/app/styles/typography/typography-demo.component.html

adds standards for the use of colons in form field labels
closes #1178

docs(formfields): form field label standards

---

projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.component.html
projects/cashmere-examples/src/lib/datepicker-sugar/datepicker-sugar-example.component.scss
projects/cashmere/src/lib/datepicker/datepicker.md

corrects several errors in the datepicker usage doc; adds sugar.js info
@isaaclyman - if you have a minute to look over the changes to this usage doc, I'd very much value your input on any other changes you might recommend.
closes #1192
closes #884

docs(datepicker): sugar.js docs

---

projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
projects/cashmere/src/lib/pop/popover-accessibility.service.ts
projects/cashmere/src/lib/pop/popover.component.ts
projects/cashmere/src/lib/pop/popover.module.ts

This isn't quite the solution we talked about @joeskeen -- I was struggling to get PopoverAnchor or PopoverComponent to hear keyboard events at anything smaller than the scope of the entire window. So this PR streamlines that, using one global keydown event listener with self-updating objects to quickly weed out as many elements as possible from the list of those that need to be notified of the event. For most keys there should be no lag. For the right arrow key, there may be slightly more lag if there are many, many elements...but there also may not be very much. See HcPopoverAccessibilityService.
I'm definitely open to other solutions, but this one is simple and hopefully will work.
Fixes #1213

refactor(popover): use shared keydown event listener

---

projects/cashmere/src/lib/toaster/hc-toast.component.ts

Remove the scale animation for consistent positioning of child toasts.  The visual difference is minimal for the positioning fix.
closes #1226

fix(toasts): consistent positioning

---

projects/cashmere-examples/src/lib/form-field-labels/form-field-labels-example.component.html
projects/cashmere-examples/src/lib/form-field-labels/form-field-labels-example.component.scss
projects/cashmere-examples/src/lib/form-field-labels/form-field-labels-example.component.ts
projects/cashmere/src/lib/form-field/hc-form-field.component.html
projects/cashmere/src/lib/form-field/hc-form-field.component.scss
projects/cashmere/src/lib/form-field/hc-form-field.module.ts
projects/cashmere/src/lib/form-field/hc-label-ext.component.ts
projects/cashmere/src/lib/form-field/hc-label.component.ts
projects/cashmere/src/lib/form-field/index.ts
projects/cashmere/src/lib/sass/form-field.scss
src/app/core/document-items.service.ts

Allow additional custom markup inside hc-form-fields.
I think this change makes form-field more dynamic.  Beyond adding the help subtext, a user could add an image, omit hc-label and make their own custom label, etc.
So Jayson - your markup will look something like this for any form-field (with a class on the span to style the help text accordingly):
```
<hc-form-field>
<hc-label>Run frequency:</hc-label>
<span>Additional instructions may be included on this line</span>
<hc-select placeholder="Select frequency:" [formControl]="selectControl">
<option value="daily">Daily</option>
<option value="weekly">Weekly</option>
<option value="monthly">Monthly</option>
</hc-select>
<hc-error>Please select the run frequency for this item</hc-error>
</hc-form-field>
```
Let me know if you have any …

fix(formfield): more flexible label content

---

projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.component.html
projects/cashmere/src/lib/form-field/hc-form-field.component.scss
projects/cashmere/src/lib/sass/form-field.scss

fix #1239, allowing labels to wrap. I got rid of some of the complex positioning magic that was being used before. It totally possible I'm missing a reason we were being so tricky with it, let me know if I did.
Also noticed that the inline labels were colored differently than other labels, so I made them match.

fix(hc-form-field): allow labels to wrap

---

projects/cashmere/src/lib/radio-button/radio-button.component.scss
projects/cashmere/src/lib/sass/radio-button.scss

A couple items in the issue were already addressed, so this just enhances keyboard accessibility by adding simple focus. Basically just makes it work more like native radios.
re #951

fix(hc-radio): add focus styles

---

projects/cashmere/src/lib/sass/form-field.scss

fix #1147
There was some css code that was turning off pointer events. The comment by the offending line of code mentioned "letting pointer events through", but it appeared to be doing the opposite.

fix(hc-form-field): allow hcPop tooltips

---

projects/cashmere/src/lib/button/split-button/split-button.component.html
projects/cashmere/src/lib/button/split-button/split-button.component.scss
projects/cashmere/src/lib/sass/button.scss

We've been seeing the following issue on smaller screens:
Adding `inline-flex` to the wrapper span prevents this behavior.

fix(button): prevent wrapping split button

---

projects/cashmere/src/lib/checkbox/checkbox.component.ts

The checkboxInput should be set to static: true and that seems to do the trick. I'm not sure how we missed that one. I only see it in Ops Console.

Set checkboxInput to static=true

---

guides/supported-angular-versions.md
guides/supported-browsers.md
projects/cashmere/package.json
src/app/guides/guides.service.ts

Add a guide to the Cashmere docs site regarding our plan for upgrading Angular versions in the future.

docs(guides): add angular version support guide

---

projects/cashmere/src/lib/sass/_breadcrumbs.scss
projects/cashmere/src/lib/sass/_cdk-overlay.scss
projects/cashmere/src/lib/sass/_functions.scss
projects/cashmere/src/lib/sass/_mixins.scss
projects/cashmere/src/lib/sass/_ng-select-theme.scss
projects/cashmere/src/lib/sass/_reset.scss
projects/cashmere/src/lib/sass/about-modal.scss
projects/cashmere/src/lib/sass/app-switcher.scss
projects/cashmere/src/lib/sass/banner.scss
projects/cashmere/src/lib/sass/button.scss
projects/cashmere/src/lib/sass/chip.scss
projects/cashmere/src/lib/sass/error-pages.scss
projects/cashmere/src/lib/sass/login-page.scss
projects/cashmere/src/lib/sass/menu-drawer.scss
projects/cashmere/src/lib/sass/navbar.scss
projects/cashmere/src/lib/sass/progress-dots.scss
projects/cashmere/src/lib/sass/progress-spinner.scss
projects/cashmere/src/lib/sass/select.scss
projects/cashmere/src/lib/sass/subnav.class.scss
projects/cashmere/src/lib/sass/subnav.scss
projects/cashmere/src/lib/sass/table.class.scss
src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.scss
src/app/components/component-viewer/shared/document-viewer/document-viewer.component.scss

Remove trailing .scss on imports to fix StackBlitz examples.
I think I've tracked down the error we're getting on StackBlitz.  Not sure when or why this started cropping up, but I was able to narrow down the scss files it was choking on.  And all of them had .scss included in their imports.  So for whatever reason that seems to be causing an issue. I went back through all our sass directory files and standardized our import syntax.
Won't be able to know for certain that this fixed the StackBlitz problem until a new version is published, but I'm pretty confident this should do it.
closes #1243

fix(scss): standardize scss imports

---

projects/cashmere-examples/src/lib/multiselect-custom-templates/multiselect-custom-templates-example.component.html
projects/cashmere-examples/src/lib/multiselect-custom-templates/multiselect-custom-templates-example.component.scss
projects/cashmere-examples/src/lib/multiselect-custom-templates/multiselect-custom-templates-example.component.ts
projects/cashmere-examples/src/lib/multiselect-custom-templates/multiselect-custom-templates-example.module.ts
projects/cashmere-examples/src/lib/multiselect-embed-checkbox/multiselect-embed-checkbox-example.component.html
projects/cashmere-examples/src/lib/multiselect-embed-checkbox/multiselect-embed-checkbox-example.component.scss
projects/cashmere-examples/src/lib/multiselect-embed-checkbox/multiselect-embed-checkbox-example.component.ts
projects/cashmere-examples/src/lib/multiselect-embed-checkbox/multiselect-embed-checkbox-example.module.ts
projects/cashmere-examples/src/lib/multiselect-overview/multiselect-overview-example.component.ts
projects/cashmere/src/lib/checkbox/checkbox.component.html
projects/cashmere/src/lib/checkbox/checkbox.component.scss
projects/cashmere/src/lib/checkbox/checkbox.component.ts
projects/cashmere/src/lib/sass/checkbox.scss
src/app/core/document-items.service.ts

This is the best way could find to get our checkboxes and ng-select to coexist. Ng-select wraps some sort of extra click handler under the covers that updates the model, and our checkbox implementation doesn't play nicely with it.
May possible to rewrite the component to avoid the need for this new property, but this is where I landed.

1267 checkbox multiselect bug

---

projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
projects/cashmere/src/lib/navbar/navbar.component.html
projects/cashmere/src/lib/navbar/navbar.component.ts

Added an additional note to the second example explaining why the mobile menu doesn't display.
But more importantly, I've hidden the mobile menu button on the navbar if a menu doesn't exist.  @isaaclyman calling that out on the first example made me realize that was an oversight.
closes #1140

fix(navbar): hide mobile menu button

---

projects/cashmere/src/lib/sass/checkbox.scss

A slightly hacky, but presumably harmless, way to fix the issue of multiline checkboxes not having their hitbox cover the area above/below the box.  Extends the padding on the label over the checkbox.
closes #1264

fix(checkbox): expanded hit area

---

.vscode/extensions.json

This will recommend to anyone opening the Cashmere project in VSCode that they install the following extensions:
* Angular language service (`angular.ng-template`)
* TsLint (`ms-vscode.vscode-typescript-tslint-plugin`)
* Prettier (`esbenp.prettier-vscode`)
Doing so will help them have better tooling and keep them on the straight and narrow while contributing to Cashmere.

build: add recommended vscode extensions configuration

---

projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
projects/cashmere/src/lib/date-range/date-range.module.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.scss
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.spec.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
projects/cashmere/src/lib/sass/date-range.scss

warn about date range being invalid on save, instead of locking the ui while selecting dates
fix #1244

fix(date range): smoother ui

---

projects/cashmere/src/lib/pop/directives/menu.directive.ts
projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
projects/cashmere/src/lib/pop/popover-anchoring.service.ts
projects/cashmere/src/lib/pop/popover.component.ts

closes #1258 
Also add some minor tweaks to enhance the keyboard navigation experience:
- shift + tab navigates you in reverse order as expected (forward tabbing was already working great)
- hitting the right arrow when on a menu item that has a submenu pops you over to the submenu. feels a little more natural and snappy to me, but let me know if it doesn't feel right to you

1258 popover menu highlight bug

---

projects/cashmere/src/lib/sass/navbar.scss

navbarlinks only display .active style when .inactive isn't present
ugh - I wasn't able to test this in context until I pushed the new build.  Didn't realize that navbarlinks can have both `.active` and `.inactive` classes attached at the same time.  So I'm rolling back one line I changed in my navbar PR yesterday and will update the build.

fix(navbar): .active style correction

---

projects/cashmere/src/lib/sass/accordion.scss
src/styles.scss

Accordion can line-wrap multiple lines of text in the toolbar.  Also eliminated some unnecessary horizontal padding from the toolbar and content area.  I suspect most devs were overriding these values to clear them - but I left the vertical padding on the content area so this wouldn't be a visual break for those who weren't overriding.
closes #1322

fix(accordion): accordion multiline toolbar

---

projects/cashmere-examples/src/lib/pagination-simple/pagination-simple-example.component.html
projects/cashmere-examples/src/lib/pagination-simple/pagination-simple-example.component.ts
projects/cashmere/src/lib/pagination/pagination.component.html
projects/cashmere/src/lib/pagination/pagination.component.scss
projects/cashmere/src/lib/pagination/pagination.component.ts
projects/cashmere/src/lib/sass/pagination.scss

Allows the component to control how much space it's buttons take up.
@corykon I liked this approach better than trying to build logic into the component to decide its size.  Feels like its better to give that control to the developer.
So we've got three sizes to choose from - `lg` is the current display (it's huge), `md` is the compressed version the would switch on the 768px break point, and `sm` just shows the prev and next buttons.
@CameronAFaust - FYI this is probably going to cause a collision with your PR because I updated the pagination-simple example - but I did make sure add the new setting as a FormControl :-)
closes #1323

feat(pagination): displayWidth parameter

---

projects/cashmere/src/lib/pagination/base-pagination.ts
projects/cashmere/src/lib/pagination/load-more-pagination.component.spec.ts
projects/cashmere/src/lib/pagination/pagination.component.spec.ts

Sanitize page number and emit events after timeout.
This will prevent the page number being sanitized
before all inputs are set.
Issue #1299
~~BREAKING CHANGE: No longer emitting events during initialization.~~

fix(pagination): check all input after timeout

---

projects/cashmere/src/lib/sass/navbar.scss

Removes the dotted line around navbarlinks in Firefox.  Submitting for @Victor1818 
closes #1329

fix(navbar): remove firefox active outline

---

projects/cashmere/src/lib/sass/navbar.scss

Underline wasn't appearing when active property was set on navbar-dropdowns

fix(navbar): active style on navbar-dropdown

---

guides/working-with-examples.md
package-lock.json
package.json
projects/cashmere-bits/package.json
scripts/new-example.ts
src/app/components/components.component.ts
src/app/core/cashmere-bits-document-items.json
src/app/core/cashmere-components-document-items.json
src/app/core/document-items.schema.json
src/app/core/document-items.service.ts
tsconfig.dev.json
tsconfig.json
tsconfig.release.json

Creating an example should only take a few minutes now, and require little reading of the
documentation! :)
Ever since I revamped the examples to make them work with StackBlitz, I've always felt a bit guilty as to how unfriendly the example creation process is.  The docs were lengthy, incomplete, and difficult to get everything right.
So I finally bit the bullet and wrote a script for generating a new example!
Now you can just run `npm run new:example` and it will scaffold All The Things needed for that example to run.  It even runs the build so that you can `npm start` and immediately start dev'ing your new example!
This work is in preparation for similar scripting for creating new Cashmere Components and Cashmere Bits (those processes will generate an "___ overview" example).  With …

build(new:example): add new example generation script

---

guides/using-and-customizing-components.md

Opt in components are working and have a proof of concept available, so this updates the documentation to indicate that they are ready to use. Removes the instructions for converting existing components, which is no longer needed. Plus a few other changes in wording.
fixes #1224

docs(customizing): update now that opt-in components are ready

---

projects/cashmere-examples/src/lib/navbar-app-switcher/navbar-app-switcher-example.component.html
projects/cashmere-examples/src/lib/navbar-overview/navbar-overview-example.component.html
projects/cashmere/src/lib/navbar/navbar-dropdown/navbar-dropdown.component.html
projects/cashmere/src/lib/navbar/navbar.component.html
projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
projects/cashmere/src/lib/pop/popover-accessibility.service.ts
projects/cashmere/src/lib/sass/navbar.scss

- popover anchor with a trigger of "click" can be opened by enter key when that anchor has focus
- tweak styles for anchor links and icons when focused
- updated examples to illustrate proper tabindex settings in the navbar
re #1361

fix(navbar): allow keyboard accessibility

---

projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
projects/cashmere/src/lib/pop/popover-accessibility.service.ts

fix #1387
Found another case I'd missed before when trying to make hcPops easier to trigger for our saavy keyboard/shortcut users. Would love to get this into a Cashmere patch release ASAP after a review & merge-  we'd like to have this working in our next PopBuilder release.

fix(popover): fix keyboard accessibility issue

---

projects/cashmere-examples/src/lib/select-compare-with/select-compare-with-example.component.html
projects/cashmere-examples/src/lib/select-compare-with/select-compare-with-example.component.scss
projects/cashmere-examples/src/lib/select-compare-with/select-compare-with-example.component.ts
projects/cashmere/src/lib/select/hc-option.directive.ts
projects/cashmere/src/lib/select/select.component.html
projects/cashmere/src/lib/select/select.component.scss
projects/cashmere/src/lib/select/select.component.ts
projects/cashmere/src/lib/select/select.module.ts
src/app/core/cashmere-components-document-items.json

re #1352 
- Added support for `compareWith` on `hc-select`
- Fixed buggy behavior when in IE
- Turned off hover styles when the component is disabled
Relied heavily on the angular codebase while implementing. Referenced this file - (https://github.com/angular/angular/blob/10.0.11/packages/forms/src/directives/select_control_value_accessor.ts#L28-L194)

1352 hc select compare with

---

projects/cashmere/src/lib/sass/form-field.scss

form-field labels now inherit their color
I think this is a good suggestion from @isaaclyman. I suppose if an app didn't have an overall color set to `$text` on `body` or on parent, then this could cause labels to change color for developers after upgrading. So probably best to get it in now with a big release coming up.  I've marked this as a breaking change so we don't forget to call it out.
closes #1304

style(form-field): label color to inherit

---

projects/cashmere-examples/src/lib/change-case-pipe-overview/change-case-pipe-overview-example.component.html

use sentenceCase instead of titleCase in the example since titleCase does not exist in v4 (renamed
to capitalCase)
re #1395

fix(change-case-pipe-overview): fix change-case incompatibility

---

guides/using-cashmere-bits.md
projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.html
projects/cashmere/src/lib/chip/chip.component.html
projects/cashmere/src/lib/chip/chip.component.scss
projects/cashmere/src/lib/chip/chip.component.ts
projects/cashmere/src/lib/sass/chip.scss
src/app/components/component-viewer/component-viewer.component.html
src/app/components/components.component.html
src/app/components/components.component.scss
src/styles.scss

Hey Joe, I made some style adjustments to your PR.  Based on how it was being used, it made more sense for that notification above the Bit tile to be a chip - but as I made that switch it exposed a few shortcomings of the component.  I added a `tight` param that we have on several other components that removes margin/padding.  And I added a `width` param so the dev can decide whether the chip should take the full width of its space (it's currently set to auto).
I also cleaned up some formatting on your guide. Let me know if you have any concerns.

feat(chips): adds blue chip type

---

projects/cashmere/src/lib/scroll-nav/nav/scroll-nav.component.ts
src/app/styles/code/code-demo.component.html
src/app/styles/table/table-demo.component.html

Gives scrollnav links focus when they are set to active - ensures the highlight border follows as the page is scrolled, but users can still keyboard navigate using the highlight to tab through links.
Also included two small fixes for search indexing two style pages I noticed needed ids on their headers.
closes #1420

1420 scrollnav active

---

package-lock.json
projects/cashmere-examples/src/lib/select-compare-with/select-compare-with-example.component.html
projects/cashmere-examples/src/lib/select-compare-with/select-compare-with-example.component.ts
projects/cashmere/src/lib/select/select.component.ts

Fixes an issue where preselected option weren't showing as selected in the control.
In a previous commit when I added the compareWith parameter, I removed a piece of code like this:
```
ngAfterContentInit() {	
if (this._valueData) {	
setTimeout(() => {	
this.writeValue(this._valueData);	
});	
}	
}
```
I thought it wasn't needed any longer, but it's important to call `writeValue()` after the view is ready for the FormBuilder + compareWith case. I added back in a similar bit of code that runs in `ngAfterViewInit` and accomplishes the same thing.
Changed the compareWith example to use angular forms instead of ngModel.

fix(hc-select): make compareWith work with FormBuilder

---

projects/cashmere-examples/src/lib/accordion-overview/accordion-overview-example.component.html
projects/cashmere-examples/src/lib/accordion-overview/accordion-overview-example.component.ts
projects/cashmere/src/lib/accordion/accordion.component.html
projects/cashmere/src/lib/accordion/accordion.component.scss
projects/cashmere/src/lib/accordion/accordion.component.ts
projects/cashmere/src/lib/sass/accordion.scss

Allow user to specify disabled property for accordion to prevent accordion from collapsing based on
some condition. Also hide accordion arrow button when disabled.
fix #1415 https://github.com/HealthCatalyst/Fabric.Cashmere/issues/1415

feat(hcaccordion): disabled hcaccordion

---

projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.html
projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.ts
projects/cashmere/src/lib/drawer/drawer-container.component.spec.ts
projects/cashmere/src/lib/drawer/drawer-container.component.ts
projects/cashmere/src/lib/drawer/drawer.component.spec.ts
projects/cashmere/src/lib/drawer/drawer.component.ts

`openStart`, `closeStart`, and `openChanged` outputs fixed; adds unit tests
@hassankhan986 deserves a medal for taking this one on, building tests around all these animationEvents was driving me up a wall.  Thanks @joeskeen for the "phone a friend" support at the end of the day to get things unstuck.
closes #1438
closes #572

Drawer unit tests / emitter fixes

---

projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts

Fixes bug on time-only input parsing. Great catch by Brent, I'm surprised this didn't crop up sooner.
The issue is that the Javascript Date object won't parse a time-only string.  It will parse a date without a time, but not the other way around.  So we have to have a placeholder date to include on time-only strings.  But it can't just be a random date because that could interfere with date comparisons on the date-range component.
So I added a placeholder value that takes the value of whatever the picker is set to, or the current date if none is set.
closes #1456

fix(datepicker): time input bug

---

guides/getting-started.md
package-lock.json
package.json
projects/cashmere-examples/src/project-template/package.json
projects/cashmere-examples/src/project-template/src/styles.scss
projects/cashmere/package.json
projects/cashmere/src/lib/sass/_menu.scss
projects/cashmere/src/lib/sass/_variables.scss
projects/cashmere/src/lib/sass/button.scss
projects/cashmere/src/lib/sass/error-pages.scss
projects/cashmere/src/lib/sass/form-field.scss
projects/cashmere/src/lib/sass/login-page.scss
projects/cashmere/src/lib/sass/picklist-pane-old.scss
src/app/components/component-viewer/shared/document-viewer/document-viewer.component.scss
src/app/foundations/fonts/fonts-demo.component.html
src/styles.scss

As per the brand updates being announced tomorrow, migrate Cashmere to Noto Sans for better international support.  Open Sans will remain the first fallback in the default font family stack in case a product isn't ready to switch over yet.
closes #970

feat(fonts): migrate to noto sans

---

README.md
projects/cashmere/README.md

@corykon - seemed like our best bet here is to link to the documentation on the site so we aren't duplicating content.  Let me know if you'd suggest any other changes.
closes #1493

docs(readme): updated readme instructions

---

projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.html
projects/cashmere-examples/src/lib/chip-basic/chip-basic-example.component.scss
projects/cashmere-examples/src/lib/icon-overview/icon-overview-example.component.html
projects/cashmere-examples/src/lib/icon-overview/icon-overview-example.component.scss
projects/cashmere/src/lib/sass/chip.scss

Having flex on the chip content is annoying because if you put any tags in the chip beyond just text, it will try and try and flex divide them within the space (which is very problematic on line wrap). I don't believe we need it, and I'd rather leave it to developers to add flex if they feel like they need it.  I've updated one example accordingly.
Also added a banner to the icon component to let folks know that its the component and the icon font is somewhere else.

fix(chip): remove flex on chip content

---

src/app/content/usage/usage-list/usage-list.component.html
src/app/content/usage/usage-list/usage-list.component.ts
src/app/content/usage/usage.component.html

Here's another go at my last PR. Hopefully this one will work better! 
I added edit buttons to each row in the abbreviations list. Clicking the button takes you to the add/change form and autopopulates some of the data for the form. 
I also changed the form validation a bit so that it now validates when you hit submit rather than having a disabled submit button and ever-present validation errors.

docs(content): add edit buttons to usage items

---

projects/cashmere/src/lib/navbar/navbar.component.ts

fixes bug where navLinks with ngIf were incorrectly added to more menu
closes #1563

fix(navbar): dynamic links

---

projects/cashmere-examples/src/lib/date-range-time/date-range-time-example.component.html
projects/cashmere-examples/src/lib/date-range-time/date-range-time-example.component.ts
projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
projects/cashmere/src/lib/date-range/date-range/date-range.directive.ts
projects/cashmere/src/lib/date-range/model/model.ts
projects/cashmere/src/lib/date-range/services/calendar-overlay.service.ts
projects/cashmere/src/lib/date-range/services/config-store.service.ts

date-range component can either be attached to the button or centered on the screen now. the unused
popperplacement param has been removed as well.
closes #1570

feat(date-range): the dev can now center the date-range component

---

projects/cashmere/src/lib/navbar/navbar.component.spec.ts
projects/cashmere/src/lib/navbar/navbar.component.ts

remove dependency on setTimeout, listen to `window:load` event
@corykon @MarielaCisneros @WistyDagel - inspiration struck today after we were talking about this, and I think I've got a fix that removes the `setTimeout` dependency.  Unfortunately, Angular's lifecycle hooks don't seem to be getting us what we want in this instance, but the standard [Window load event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) does.  It's fired after the page is fully rendered, which is what we need to get a proper width calculation on all the link elements.
So I _think_ this works...at least everything I could think to test seemed to check out.  Can you all give it a try as well?  And @pheebner - not sure if you can test it out before the fix is merged, but would love to hear your …

fix(navbar): calculate link widths after page load

---

projects/cashmere/src/lib/sass/_code-highlight.scss
projects/cashmere/src/lib/sass/_colors.scss
projects/cashmere/src/lib/sass/_typography.scss
src/app/components/component-viewer/shared/document-viewer/document-viewer.component.scss
src/app/foundations/code/code-demo.component.scss
src/app/foundations/typography/typography-demo.component.scss
src/styles.scss
tools/dgeni/templates/method.template.html

re #956 Decided against doing a dark mode. It would've been difficult to show it without more intensive changes to the way we display markdown.
Changes are pretty minimal, but code blocks are cleaner and now use cashmere colors. Before on the left, and after on the right

fix(code styles): refresh code block styles

---

projects/cashmere/src/lib/drawer/drawer.component.ts

prevent scrollbar from appearing when drawer is closed on Safari
closes #1559

fix(drawer): safari scrollbar fix

---

src/app/content/personas/persona-org/persona-org.component.html

adds "i" to spell Organization correctly in this headline on this page (https://cashmere.healthcatalyst.net/content/org-chart)

fix(docs): typo error

---

src/app/shared/markdown/markdown.directive.ts

removes unintentional article tag on breadcrumb html
closes #1711

docs(markdown): fix breadcrumbs styles

---

projects/cashmere-examples/src/lib/environment-switcher-overview/environment-switcher-overview-example.component.ts
projects/cashmere/src/lib/env-switcher/env-switcher.component.html

fix(env switcher): don't show info icon if no description is available

---

projects/cashmere/src/lib/navbar/navbar-dropdown/navbar-dropdown.component.html
projects/cashmere/src/lib/navbar/navbar-link/navbar-link.component.html
projects/cashmere/src/lib/sass/navbar.scss

fix #1673
Took some battling, but eventually got it to repro and was able find a fix.
Solution was to use 'force-active' class instead of just 'active', because we were using an 'active' class for the built in route-based underlining and sometimes it was causing conflicts.

fix(navbar): fix `active` input

---

projects/cashmere-examples/src/lib/popover-fixed-position/popover-fixed-position-example.component.html
projects/cashmere-examples/src/lib/popover-fixed-position/popover-fixed-position-example.component.scss
projects/cashmere-examples/src/lib/popover-fixed-position/popover-fixed-position-example.component.ts
projects/cashmere/src/lib/pop/index.ts
projects/cashmere/src/lib/pop/popover-anchoring.service.ts
projects/cashmere/src/lib/pop/types.ts
src/app/core/cashmere-components-document-items.json
src/app/foundations/foundations-routes.module.ts

force the popover to update after a reposition event
@corykon the issue here (which you already called out in a comment), is that the popover needs to get destroyed for overlay positioning changes to take effect.  Fortunately you already had the code in place to do that, so just needed to connect the reposition event.
I also reordered the popover examples while I was in there.
closes #1647
closes #1748
closes #1721

fix(popover): update after reposition

---

guides/contribution-guide.md
guides/getting-started.md
package.json

`npm run build` still fails the second time you run it, so this PR sets up a workaround. As needed, devs can use `npm run build:dev` while working on contributions and avoid the issues caused by the Bit build.
An issue to really fix the build issue was added here- #1750

build(ivy): setup workarounds for known build issues

---

projects/cashmere/src/lib/sass/_functions.scss
projects/cashmere/src/lib/sass/datepicker.scss
projects/cashmere/src/lib/sass/form-field.scss
projects/cashmere/src/lib/sass/progress-dots.scss
projects/cashmere/src/lib/sass/progress-spinner.scss
projects/cashmere/src/lib/sass/stepper.scss

I had changed us over to `math.div()` as called for by sass. https://sass-lang.com/documentation/breaking-changes/slash-div
`Math.div()` isn't playing nicely with stackblitz when imported by a library, so I switched back. We'll get warnings again with this when building... but shouldn't break anything.
fix #1757

build(sass): reverting change from "/" to math.div

---

projects/cashmere-examples/src/project-template/tsconfig.json
scripts/build-examples.ts
src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.ts

Hallelujah!
Started with a working Ivy-based stackblitz example, and kept copying stuff back and forth until I tracked down the changes needed. Found that Ivy wasn't enabled in the tsconfig file, and stackblitz didn't like the way were trying to import our bit module.
Also made a change to not hide debug tools by default. I find them useful and I'm sure other devs will, too.

fix(stackblitz): enable Ivy and fix bit module refs for stackblitz

---

projects/cashmere-examples/src/lib/form-field-tight/form-field-tight-example.component.html
projects/cashmere-examples/src/lib/form-field-tight/form-field-tight-example.component.scss
projects/cashmere/src/lib/form-field/hc-form-field.component.scss
projects/cashmere/src/lib/form-field/hc-form.directive.ts

fixes style collision and bug when tight is applied to form
@corykon - I noticed when fixing this bug that if `tight` was applied to an `hcForm`, it wasn't being applied to any descendent `hc-form-fields`.  I guess that bug probably showed up on one of our Angular upgrades but I totally missed it.  You can see it on the current Cashmere site in the last FormField example.  Anyway, the bug is fixed in this PR.
closes #1487

fix(form-field): inline/tight style collision

---

projects/cashmere/src/lib/pop/popover-anchoring.service.ts

@corykon @aaronbrethorst - do you think I need to remove the event listener I'm adding here?  When the popover closes, the CDK overlay element that it's attached to is destroyed. Wasn't sure if that takes care of the garbage collection for me or if we still need to removeEventListener.
closes #1390

fix(popover): allow right-clicks to close popovers

---

projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.html
projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.ts
projects/cashmere/src/lib/toaster/hc-toast-options.ts
projects/cashmere/src/lib/toaster/hc-toast.component.html
projects/cashmere/src/lib/toaster/hc-toast.component.scss
projects/cashmere/src/lib/toaster/hc-toast.component.ts
projects/cashmere/src/lib/toaster/hc-toaster.module.ts
projects/cashmere/src/lib/toaster/hc-toaster.service.ts

ability to set custom images / icons on standard toasts
@corykon @joeskeen - making the custom image 30 x 30px like the icons felt too small to me.  So for custom images I made it 60x60px instead.  That work?  Any real benefit to giving the dev another param to set that image size?
closes #1253

feat(toasts): custom image

---

.nvmrc
guides/contribution-guide.md

Mention in the Contribution Guide that the project does not build reliably under the current Node LTS version (node 16 + npm 8), and that the previous LTS version, 14, should be use instead.
Also include link to `nvm`, which makes it easy to maintain multiple Node installations on the same machine, and add an `.nvmrc` file to make it easier to use the correct Node version when `nvm` is employed.

docs(node): specify required node version

---

projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.html
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
projects/cashmere/src/lib/date-range/model/model.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.spec.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
projects/cashmere/src/lib/date-range/services/config-store.service.ts
projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts

Allows date ranges to be open-ended on either side to allow for selecting ranges like "Feb 24, 2022 or earlier" or "Feb 24, 2022 or later".
Closes #1297

feat(date-range): make start & end dates optional

---

projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.spec.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts

A date range picker where 'to date required' and 'from date required' are set to `false` should allow a completely empty range with two null values for the date to be created. This change amends the range validation function to support the aforementioned scenario and adds a test to verify it.
Closes #1833

fix(date-range): allow blank dates when to/from dates aren't required

---

projects/cashmere/src/lib/instance-switcher/instance-switcher.component.html

Hide the instance close buttons when there is only one instance left.

fix(instance-switcher): prevent last instance from closing

---

projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.html
projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.scss
projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.ts
projects/cashmere/src/lib/tabs/tab-set/tab-set.component.html
projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts

Adds the ability to pass -1 to selectTab to deselect all.  
A little tricky when using tabs with routerLinks - because when deselecting I don't think we want to change the current route.  So in that instance I'm really just hiding the routerOutlet until a tab is selected again.
I also realized while I was in there that when using tabs with routerLinks, the selectTab function wasn't actually routing when called :-(  So that's been corrected here.
The first tab example has been updated to demonstrate deselecting.
closes #1870

fix(tabs): deselect all tabs

---

projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts

In certain situations, tabs will not render at the same time as the tab content. This fixes that
issue.

fix(tab-set): fix tab rendering

---

guides/linking-a-local-app-to-cashmere.md
src/app/guides/guides.service.ts

Adds documentation for how to set up to debug a local version of Cashmere with npm link

docs: add npm link docs

---

guides/getting-started.md
guides/styles/login.md
package-lock.json
package.json
projects/cashmere-examples/src/lib/date-range/date-range-example.component.scss
projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.scss
projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.scss
projects/cashmere-examples/src/lib/drawer-overlay/drawer-overlay-example.component.scss
projects/cashmere-examples/src/lib/drawer-side/drawer-side-example.component.scss
projects/cashmere-examples/src/lib/multiselect-custom-templates/multiselect-custom-templates-example.component.scss
projects/cashmere-examples/src/lib/progress-dots/progress-dots-example.component.scss
projects/cashmere-examples/src/lib/progress-spinner/progress-spinner-example.component.scss
projects/cashmere-examples/src/lib/subnav-overview/subnav-overview-example.component.scss
projects/cashmere-examples/src/lib/tile-overview/tile-overview-example.component.scss
projects/cashmere-examples/src/lib/toaster-overview/toaster-overview-example.component.scss
projects/cashmere-examples/src/project-template/src/styles.scss
projects/cashmere/src/lib/multiselect/multiselect.md
scripts/postbuild.js
src/app/foundations/icons/icon-guide.component.html

Some changes to the documentation, examples, and build scripts around how we use sass. There have been changes around the way SASS imports within angular.
- tilde imports are deprecated and don't work in most cases, so had to switch to relative paths or absolute paths in some places
- in examples, the node_modules paths don't compile, but `@healthcatalyst/../..` paths do
I'm not in a hurry to get this PR in, but wanted to show what I'm finding that works. I wish I could double check this in stackblitz, but Cashmere 13 still isn't coming up. 
We should probably regroup and look together at all the issues we've seen with Angular & Cashmere 13, talk about how to avoid those in the future for major releases. Maybe some more diligent testing in a few projects before announcing the update.

Getting started update

---

projects/cashmere/src/lib/tabs/tab-set/tab-set.component.html

remove wrapper div for deselecting router based tabs
@isaaclyman - thanks for finding this one and troubleshooting where the problem was coming from.  A bit of sloppy programming on my part, in going back and testing there really isn't any need for that wrapper div.  I can put the same logic into the `ngIf` that was already on the `router-outlet` and everything still works like it needs to when you call `selectTab(-1)` to deselect router based tabs.
closes #1903

fix(tabs): remove unecessary div

---

projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.html
projects/cashmere-examples/src/lib/drawer-menu/drawer-menu-example.component.ts
projects/cashmere-examples/src/lib/drawer-side/drawer-side-example.component.html
projects/cashmere/src/lib/drawer/drawer-container.component.html
projects/cashmere/src/lib/drawer/drawer-container.component.ts
projects/cashmere/src/lib/drawer/drawer.component.scss
projects/cashmere/src/lib/drawer/drawer.component.ts
projects/cashmere/src/lib/drawer/menu-drawer/menu-drawer.component.ts
projects/cashmere/src/lib/sass/drawer.scss

adds ability to turn drawer animation on or off
@robertjorg - let me know how this looks.  The only gotcha is that the animation disable will actually be on `hc-drawer-container` rather than `hc-drawer`.  The reason being there is animation on both the drawer and the content.  So the toggle needs to be on the container so it can enable/disable both.
closes #1901

feat(drawer): animated param

---

projects/cashmere/src/lib/modal/modal-window.component.scss
projects/cashmere/src/lib/modal/modal-window.component.ts
projects/cashmere/src/lib/modal/modal.service.spec.ts
projects/cashmere/src/lib/modal/modal.service.ts

fix #1913
A change to avoid querying for `hc-modal` within the modal service. Avoids a crash for cases where consuming application wraps the `hc-modal` in an *ngIf.

fix(modal): avoid errors when used with *ngIf

---

projects/cashmere-examples/src/lib/table-filter/table-filter-example.component.html
projects/cashmere-examples/src/lib/table-sort/table-sort-example.component.html
projects/cashmere/src/lib/app-switcher/app-switcher.component.ts
projects/cashmere/src/lib/button/button.component.ts
projects/cashmere/src/lib/datepicker/calendar-body/calendar-body.component.ts
projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
projects/cashmere/src/lib/env-switcher/env-switcher.component.ts
projects/cashmere/src/lib/modal/modal-overlay.component.ts
projects/cashmere/src/lib/modal/modal-window.component.ts
projects/cashmere/src/lib/sass/table.class.scss
projects/cashmere/src/lib/sass/table.scss
projects/cashmere/src/lib/sort/sort-header.ts
projects/cashmere/src/lib/table/cell.ts
projects/cashmere/src/lib/table/index.ts
projects/cashmere/src/lib/table/row.ts
projects/cashmere/src/lib/table/table.module.ts
projects/cashmere/src/lib/tabs/tab/tab.component.ts
projects/cashmere/src/lib/toaster/hc-toast.component.ts
src/app/components/component-viewer/shared/document-viewer/document-viewer.component.ts
src/app/core/cashmere-components-document-items.json
src/app/styles/table/table-demo.component.html

adds the index-cell type for row number columns
@jonest @corykon let me know what you think of this approach.  My original approach was to add a `rowNumbers` param to hc-table, and then have it automatically add a column with numbers.  But the more I thought about it, the goal with hc-table is to be as flexible as possible, and it seemed like that kind of restricted the value of this to a pretty narrow use case.
So instead I added a new cell type called `hc-index-cell` which can be added to a header or body cell.  When applied it narrows the width and padding of the cell and applies the darker background.  It still respects the padding on sort headers though, and works fine with tight tables.
I updated the first two examples to demonstrate the new cell type.
closes #1816

feat(table): hc-index-cell

---

projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.html
projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.ts
projects/cashmere-examples/src/lib/measurable-vertical/measurable-vertical-example.component.html
projects/cashmere-examples/src/lib/measurable-vertical/measurable-vertical-example.component.ts

@bskeen - just a small fix here that should get rid of the inconsistent behavior on initial load.  It's annoying to have to add an empty `setTimeout` but that seems to be the silver bullet to make sure the widths get calculated only after everything is finished rendering.
I also made an adjustment to the style of the buttons in the button row so they look different from the action buttons.  Just makes the functionality of the example a little clearer.
closes #1909

fix(measureable): example load fix

---

projects/cashmere-examples/src/project-template/package.json

Frustrating to have to do this - but I hate having broken Stackblitz links while we wait for a response from them.  What do you both think?

docs(stackblitz): temporary stackblitz version fix

---

projects/cashmere/src/lib/pop/directives/menu-item.directive.ts
projects/cashmere/src/lib/pop/directives/menu.directive.ts
projects/cashmere/src/lib/pop/directives/popover-anchor.directive.ts
projects/cashmere/src/lib/pop/pop.md
projects/cashmere/src/lib/pop/popover-anchoring.service.ts

I think I actually cracked this one!  As per the request from the Vitalware team, `hcMenu` items with submenus now automatically get their trigger type set to hover.  And I've built enough awareness into the menu directive to know when to close a submenu and when not to.  I think it's working as expected, but please load up this branch and test out the "Popover Menu" example in the Popover component section.  Thanks!
closes #1469

feat(hcmenu): submenus hover trigger

---

src/app/app.component.html

Tweaking the Web Apps dropdown to have `</> Angular Components` and `</> React Components`. The react components links over to `react-cashmere` storybook.
I have also made the `react-cashmere` library public.

docs(react-cashmere): adding link to react-cashmere GH pages

---

projects/cashmere/package.json

Remove some references in package.json that are no longer relevant and cause problems for stackblitz. When we upgraded to angular 13, it changed what gets bundled and passed into the dist folder.
My understanding of the properties I've removed in the library's package.json is pretty lacking, but I built a new library using the cli (v13) and angular (v13) and this seems to match that better, and doesn't have any references to non-existent files.
Link to the github issue where we got the tip on what to fix: https://github.com/stackblitz/core/issues/1903#issuecomment-1223762269

build(package.json): fix stackblitz examples

---

projects/cashmere/package.json

We won't publicize this new version... more pushing it out and publishing for the sake of testing if it fixes stackblitz.
Will go back and change the stackblitz examples package.json to point to the latest cashmere version after validating that this change works. 
```
"@healthcatalyst/cashmere": "*",
```

Fix stackbltiz

---

projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
projects/cashmere/src/lib/datepicker/datepicker-content/datepicker-content.component.html
projects/cashmere/src/lib/datepicker/datepicker-content/datepicker-content.component.ts

As per Vitalware's request, UX improvement to the datepicker to select and close the datepicker when the Today button is clicked (rather than just highlighting the current date but not selecting it).
closes #1962

fix(datepicker): today click selects and closes

---

projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts

prevent selectedTabChange from emitting twice on init
closes #1930

fix(tabset): selectedtabchange emit fix

---

projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts

I added an input that selects which tab is currently shown without emitting a tab change event.
feat 1972

feat(tab-set): add selected tab input to tab set

---

projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.ts
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts
projects/cashmere/src/lib/datepicker/datepicker.component.spec.ts
projects/cashmere/src/lib/datepicker/datepicker.component.ts

Expose support for `allowBlankValues` in the DatePicker component.
fix #1984

fix(datepicker): allow blank values with new datepicker option

---

projects/cashmere/src/lib/drawer/drawer.component.ts

Immediately return a resolved Promise from the Drawer component's `toggle()` function if the desired state of the Drawer matches the current state of the Drawer. This will prevent the Drawer from getting 'stuck' open when an open Drawer is asked to open itself.
This allows callers to request a particular state without worrying about the Drawer's current state.
fix #2005

fix(drawer): prevent drawer from getting 'stuck'

---

projects/cashmere-examples/src/lib/tabs-horizontal/tabs-horizontal-example.component.html
projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts
projects/cashmere/src/lib/tabs/tab/tab.component.ts

Scrolls a tab into view when clicked or selected with selectTab
I kept the use case pretty narrow here because `scrollIntoView` can be pretty annoying if it's firing to often or in the wrong context.  So this is only triggered on horizontal tabs with arrow overflow that's active.  The developer can also elect to turn off scrollIntoView when they call the `selectTab` function.
To test, go to the Tabs page, and set the Horizontal Tabs example to "Arrows" overflow.  Then click the "Select Last Tab" button.
closes #2042

fix(tabs): arrow overflow scrollIntoView

---

projects/cashmere/src/lib/button-toggle/button-toggle-group.component.ts
projects/cashmere/src/lib/checkbox/checkbox.component.ts
projects/cashmere/src/lib/date-range/date-range/date-range.directive.ts
projects/cashmere/src/lib/file-uploader/file-uploader.component.ts
projects/cashmere/src/lib/radio-button/radio.ts
projects/cashmere/src/lib/select/select.component.ts
projects/cashmere/src/lib/slide-toggle/slide-toggle.component.ts

resolves bug where writevalue is called after a form control is removed
@bskeen - this was an interesting one!  As it turns out `writeValue` on the FormControl is getting called when the previous control is being removed, but it's getting called with the value of the new control 😬 that definitely seems like an Angular bug.  I also noticed that `ngDestroy` isn't being called when the control is removed - which is concerning that there's a memory leak in Angular here too.  
It was kinda tricky to figure out how to identify when the control has actually been removed given the above, but I discovered that the registered functions like `OnChange` turn into no operation after being removed.  So that was the way I could determine if it's a legit `writeValue` call or not.
On SlideToggle and …

fix(form-field): writevalue on remove bug

---

projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.html
projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.scss
projects/cashmere-examples/src/lib/measurable-overview/measurable-overview-example.component.ts
projects/cashmere-examples/src/lib/measurable-vertical/measurable-vertical-example.component.scss
projects/cashmere-examples/src/lib/measurable-vertical/measurable-vertical-example.component.ts
projects/cashmere/src/lib/instance-switcher/instance-switcher.component.scss

FYI @bskeen - if you were noticing any weird style things going on while using the instance switcher, I think this patch will help.  You were doing the right thing to try and keep your styles as flat as possible, but where you were augmenting styles for other components, we want to make sure they stay within the scope of the Instance Switcher (see the changes to the scss file).
I also made a couple adjustments to the Measureable examples so we weren't fighting the "waiting for the page to render" issues.  So now it just starts empty and lets the user add buttons, which is probably better to keep the example from getting overwhelming.
closes #2056

fix(instance-switcher): prevent style collisions

---

package-lock.json
package.json
src/app/content/content.module.ts
src/app/content/usage/usage-list/usage-list.component.html
src/app/content/usage/usage-list/usage-list.component.ts
src/app/content/usage/usage.ts

Remove dependency on `ng-google-sheets-db` package which causes `npm i` to fail with the Angular 14 upgrade.

docs(content-usage): remove ng-google-sheets-db

---

projects/cashmere-examples/src/lib/input-required/input-required-example.component.html
projects/cashmere-examples/src/lib/input-required/input-required-example.component.scss
projects/cashmere-examples/src/lib/input-required/input-required-example.component.ts
projects/cashmere/src/lib/checkbox/checkbox.component.ts
projects/cashmere/src/lib/datepicker/datepicker.component.spec.ts
projects/cashmere/src/lib/file-uploader/file-uploader.component.ts
projects/cashmere/src/lib/input/input.directive.ts
projects/cashmere/src/lib/radio-button/radio.ts
projects/cashmere/src/lib/select/select.component.ts
projects/cashmere/src/lib/slide-toggle/slide-toggle.component.ts

make sure error states are reset have form resets
closes #2124
@guille-gomez this one was a real mind bender, notes below (I've also updated an example on the inputs page with these notes):
- The big trick here is that you have to make sure after a form submit you are resetting your form to submitted = false.  As best as I can tell, there are two ways to do that - I show both of them in the example.  You can use resetForm() on NgForm.  Or you can include a button inside your form with `type="reset"`.  The second is old school HTML, but it still does the trick and removes submitted from your form.
- That said, I did have to add a `setTimeout` to all our ngControl.statusChanges subscriptions, because we need to be sure that the error state check is happening after submitted states have been …

fix(form-field): error check on form reset

---

projects/cashmere/src/lib/navbar/navbar-dropdown/navbar-dropdown.component.html

set horizontal align to start rather than center on menus

fix(navbar): dropdown pop alignment

---

projects/cashmere/src/lib/sass/modal.scss

New default height so that tall modals won't bleed off screen. 
re #1902

feat(modal): add default max height on modal body

---

projects/cashmere-examples/src/lib/table-sticky/table-sticky-example.component.html
projects/cashmere-examples/src/lib/table-sticky/table-sticky-example.component.scss
projects/cashmere-examples/src/lib/table-sticky/table-sticky-example.component.ts
projects/cashmere/src/lib/sass/table.class.scss
projects/cashmere/src/lib/sass/table.scss
projects/cashmere/src/lib/table/index.ts
projects/cashmere/src/lib/table/table-container.directive.ts
projects/cashmere/src/lib/table/table.module.ts
src/app/core/cashmere-components-document-items.json
src/app/styles/table/table-demo.component.html
src/app/styles/table/table-demo.component.scss
src/app/styles/table/table-demo.component.ts

We had a few really old issues out there about sticky table headers being buggy and not well documented. Now that we're not supporting IE11, this become easier.
**Component**
**CSS-only Examples**
re #889 
re #685 
fix #1207

889 sticky table headers

---

projects/cashmere/src/lib/sass/table.class.scss
projects/cashmere/src/lib/sass/table.scss

Tried out the new sticky header code in CDP config UI. Found one little issue where right side border can bleed through from behind sticky header.

fix(table): update styles for sticky headers

---

projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.html
projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.ts
projects/cashmere/src/lib/search-bar/search-bar.component.ts

I figured `debounce` should be configurable. I was going to add it to the example as well but, this implementation doesn't allow altering the debounce time after `ngOnInit` has fired. 
This didn't seem like a big enough reason for me to alter the implementation, but, let me know if you disagree and I'm sure I can come up with something.

feat(search-bar): add debounce input

---

projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.html
projects/cashmere-examples/src/lib/search-bar-overview/search-bar-overview-example.component.ts
projects/cashmere/src/lib/input/clear-input.component.ts
projects/cashmere/src/lib/search-bar/search-bar.component.html
projects/cashmere/src/lib/search-bar/search-bar.component.ts

re #2189
Add a `clearClicked` event emitter that came up as a need for a CDP config UI use case.

feat(search bar): add event for clear button click

---

projects/cashmere-examples/src/lib/input-required/input-required-example.component.html
projects/cashmere-examples/src/lib/input-required/input-required-example.component.ts
projects/cashmere/src/lib/input/input.directive.ts

Because there is no way to listen for changes to the `touched` state on an Input, we use the blur event as a proxy.  But in instances where the developer is calling `markAsTouched` or `markAllAsTouched`, a blur event won't be fired, and the developer will expect error state checking to occur.  This update patches the native functions to call Cashmere error state error checking.

fix(input): error check on markAsTouched

---

projects/cashmere-examples/src/lib/select-forms/select-forms-example.component.html
projects/cashmere-examples/src/lib/select-forms/select-forms-example.component.scss
projects/cashmere-examples/src/lib/select-forms/select-forms-example.component.ts
projects/cashmere-examples/src/lib/select-placeholder/select-placeholder-example.component.html
projects/cashmere-examples/src/lib/select-placeholder/select-placeholder-example.component.scss
projects/cashmere-examples/src/lib/select-placeholder/select-placeholder-example.component.ts
projects/cashmere/src/lib/select/select.component.html
projects/cashmere/src/lib/select/select.component.ts
projects/cashmere/src/lib/select/select.module.ts

Fixes #2207, fixes #2208, fixes #2209.
This PR fixes the behavior of hc-select when a non-string `placeholderValue` is set on page load, and when the option elements in ng-content change after page load.

hc-select bugs: placeholderValue and ng-content changes

---

projects/cashmere/src/lib/sass/search-bar.scss

The icon in the search bar was repeating itself when switching to 'tight' styling.

fix(search-bar): the background image repeating.

---

projects/cashmere/src/lib/form-field/hc-form-field.component.html
projects/cashmere/src/lib/form-field/hc-form-field.component.ts

fix(input): clicking suffix or prefix calls focus()

---

projects/cashmere/src/lib/sass/sidenav.scss
projects/cashmere/src/lib/sidenav/sidenav.component.html
projects/cashmere/src/lib/sidenav/sidenav.component.scss

fix(sidenav): fix text overflow issues

---

projects/cashmere/src/lib/drag-list/drag-list.component.html
projects/cashmere/src/lib/drag-list/drag-list.component.scss
projects/cashmere/src/lib/drag-list/drag-list.component.ts
projects/cashmere/src/lib/sass/drag-list.scss

Previously hard-coded to `max-height: 300px`. Now by default grows to content height, but a max-height can be set on the root element and each column will scroll independently.

fix(draglist): make height flexible

---

projects/cashmere/src/lib/sidenav/sidenav.component.html

Tiny little fix: I realized that hcTooltips weren't showing for tabs with nested links, like this one.

fix(sidenav): fix tooltip for collapsed tabs with nested links

---

projects/cashmere/src/lib/sidenav/sidenav.component.html
projects/cashmere/src/lib/sidenav/sidenav.component.ts

Testing out the new sidenav, and PopAnalyzer found an issue where clicking a favorited item would activate one of the main tabs

fix(sidenav): fix issue with favorites

---

projects/cashmere/src/lib/sass/sidenav.scss
projects/cashmere/src/lib/sidenav/sidenav.component.html

There are a lot of formatting changes but all I did is change the tabs in the side Nav to use anchors.

feat(sidenav): use anchor tags for native context menu support

---

projects/cashmere/src/lib/tabs/tab-set/tab-set.component.ts

Prevent an error from being thrown when the activeTab is null or undefined.

fix(tab-set): fix issue on selectTab

---

guides/accessibility/writing-for-accessibility.md
src/app/accessibility/accessibility-routes.module.ts

Relabeled an accessibility section from 'ux writing' to 'writing for accessibility', for clarity. The prev label wasn't wrong, but we have another section in the app named the same thing so I got confused.
re #2307

docs(accessibility): renamed document

---

projects/cashmere-examples/src/lib/sidenav-tab-group/sidenav-tab-group-example.component.html
projects/cashmere-examples/src/lib/sidenav-tab-group/sidenav-tab-group-example.component.ts
projects/cashmere/src/lib/sass/sidenav.scss
projects/cashmere/src/lib/sidenav/sidenav.component.html
projects/cashmere/src/lib/sidenav/sidenav.component.scss
projects/cashmere/src/lib/sidenav/sidenav.component.ts
projects/cashmere/src/lib/sidenav/sidenav.models.ts

- fixed minor css bug with dark mode sidenavs
- added some new options
- custom css classes on tabs and group headers
- ability to handle clicks on group headers
- option to hide or not hide children links of tab groups when collapsing the sidebar

2312 sidenav updates

---

projects/cashmere/src/lib/sass/table.class.scss
projects/cashmere/src/lib/sass/table.scss

- Sticky styles would break when used in conjunction with the css sort headers, due to some styles being overriden
- Also noticed a sizing issue would happen on left aligned sort icons if used in the last column of a table with borders. Fixed that as well.
re #2199

fix(table): fix sticky header styles

---

projects/cashmere/src/lib/toaster/hc-toast.component.html
projects/cashmere/src/lib/toaster/hc-toast.component.scss

make sure content is centered, even if a header is not provided
fix #2324

fix(toast): vertically center toast content

---

projects/cashmere/src/lib/sass/sidenav.scss
projects/cashmere/src/lib/sidenav/sidenav.component.html
projects/cashmere/src/lib/sidenav/sidenav.models.ts

when sidenav is collapsed and group header is being displayed, you can present a different group label
re #2326

feat(sidenav): can provide alt header for groups

---

projects/cashmere/package.json

Currently, we have a section on the Cashmere website suggesting that consumer Angular versions do not need to track the version used by Cashmere, but Angular CDK requires a major version match, while the rest do not. Without this, it's not possible, in practice, to upgrade to a newer version of Angular until Cashmere is also updated.
Tested this with Pop Analyzer locally and I was able to use Angular v18 without compilation issues and did not see any glaring issues when smoke testing.

Allow @angular/cdk peer dependency greater than current version
